### ISSUE TITLE
章節編號漢化

### ISSUE THREAD

**Issue by loveakai** [wengan-li/ncku-thesis-template-latex#10]
您好！我又有一些問題想要請教您了，在此先為打擾您說聲抱歉。
因我使用中文書寫論文的緣故，希望論文的章節可以用中文顯示，比如說呈現「第一章」而非「第1章」。目前我想到的困難點在於也許latex中的中文數字順序可能沒有定義，所以可能無法簡單的使用指令轉換。不過因為我的章、節數都不會超過十，所以或許有可能我寫一個對照的指令讓他自動將1-10數字轉中文？
另外因為章節牽涉到會自動生成目錄，所以也覺得需要考慮除了自動轉換以外，還要讓他可以正確的呈現在目錄中。不知道您有什麼想法嗎？
還有另一個問題，我在寫論文的過程中有用到\item{}這樣的指令，但我發現在\item{}中的文字的行距相較於\begin{enumerate} \end{enumerate}之外的東西來得小，不知道是不是latex會自動調整行距，但因為行距的差距還蠻明顯的，所以想請問是否可以在哪邊加入指令，讓整篇論文的行距都是相同的呢？
謝謝您撥冗解答。

**Comment by wengan-li** [comment]
有關呈現「第一章」而非「第1章」, 這的確在latex好像沒有中文數字順序相關的定義, 所以暫時沒有看到看起來能用的工具和command, 這幾天我去增加這個功能.

目錄那個不用擔心, 如果在內文那邊顯示正常, 正常來講目錄都會使用同一些的字, 除非底部的command設定錯誤.

enumerate那邊是有設定行距的東西, 但那個我都沒有太熟, 我都要去查查看.
你說\item{}中的文字的行距比較小, 請問能否有一個例子說明呢 ?
是"item和item之間", "item的內文", "進入enumerate, 文章跟第一個item或最後一個item的之間的空間", 或是其他呢 ?
我有點不太懂你意思, 能否再詳細一點呢 ?

**Comment by loveakai** [comment]
是的，先謝謝您了:)

**Comment by loveakai** [comment]
補充說明關於行距的部分，可以參考我的截圖
[https://www.dropbox.com/s/poh2nx6zvt7jinu/%E8%9E%A2%E5%B9%95%E6%88%AA%E5%9C%96%202016-05-05%2023.59.21.png?dl=0]
可以看出item之間比較緊密，但正文之間比較寬鬆。

**Comment by wengan-li** [comment]
我幫你的圖轉放在github中了
那你就不用煩悶要留在dropbox中
![2016-05-05 23 59 21](https://cloud.githubusercontent.com/assets/6211564/15074265/8203ea50-13d0-11e6-9680-8b0f7b86b315.png)

**Comment by wengan-li** [comment]
這個是還在設計的行距
我發現item之間跟正文之間都好像一樣密
你覺得如何呢 ?

![dev-item](https://cloud.githubusercontent.com/assets/6211564/15074315/da3dd26c-13d0-11e6-9a40-77c606e604b1.png)

**Comment by loveakai** [comment]
首先謝謝您幫我把圖片發上來。
我認為您設計後的這個很漂亮，我理想中是item之間的行距不會縮小，跟之前版本的正文一樣寬，這樣就是最好的設定了。

**Comment by wengan-li** [comment]
[請去先更新模版到最新版](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.4.0), 你的情況主要把'ncku'資料夾更新則可.

你要的「第一章」而非「第1章」
請在conf.tex中使用\ChapterTitleInChi和\ChapterTitleNumInChi.

但由於這是由package<zhnumber>所提供的功能,
故你同時可能需同時更新MiKTeX,
請看[新的說明文件](https://github.com/wengan-li/ncku-thesis-template-latex-sample)中的章節'3.3.3 更新MiKTeX' 去介紹如何更新MiKTeX.
不過我都推薦你連Texmaker都更新到最新版.

更新後, 記得在'ncku/configure.tex'中補回你在#11 提到的內容.

**Comment by loveakai** [comment]
您好，我試用的結果如下：
1. 章的部分可以正確使用中文顯示，但節的部分仍然會顯示數字。例如1.1，不知道這部分如果是顯示一.1這樣會不會比較好呢？
2. 我的item之間仍然會產生間隔較小的現象。跟您在上面回覆展示的不太一樣。
3. 我產生了一些warning message，不確定會不會有什麼影響。

2.3的情況如圖：
[https://www.dropbox.com/s/nzrr9i9n0ltax2h/%E8%9E%A2%E5%B9%95%E6%88%AA%E5%9C%96%202016-05-11%2019.33.50.png?dl=0](url)

裡面字看起來比較扁只是顯示器的關係而已，實際上pdf的檔案字的高度是正確的。

**Comment by wengan-li** [comment]
你直接把圖拖進下面那個輸入的地方
就可以看到它在upload的
等它upload完就會自動換成一段的URL的
![2016-05-11 19 33 50](https://cloud.githubusercontent.com/assets/6211564/15201928/7beb8c8e-1828-11e6-9505-920259052fcf.png)

**Comment by wengan-li** [comment]
1.
這個是一個值得討論跟個人喜好的議題呢
對你來講可能是 '一.1.1' 比較好
對我來講可能是 '1.1.1' 比較好
真的很個人主觀.

但你提到出來,
的確值得提供這功能出來,
直接交由同學們自己決定好了.
我在這新一版弄弄.

2.
唔  我再研究看看.
我可能弄到了item的空間.

而且是我錯覺嗎 ?
我覺得你給的2張圖字型不一樣,
是我都弄到字型的問題嗎 ?
因為package順序不一樣, 字型會改變的.

3.
warning真的很見人見智.

Badbox那類的, 基本上沒有錯太嚴重的話,
是看不出什麼的錯, 所以是不影響內容.

Warning的話, 例如你看第1~3個,
第1個是package內部warning,
只是一個通知說'這是實驗中的package, 使用的話自行負責任何後果'.
第2個是你論文title有使用'\\'來斷行, 但package不給有這個字,
所以通知你說它會處理掉.
第3個是說package所使用的英文字型'Times New Roman',
無法提供某個字, 所以轉用了其他字型.
這些內容能提供到一些有用的資料,
但基本上warning基本上是不理它的,
因為太容易有了, 而且不一定需要處理.

你要在意的是紅字的Error就是了,
那個會令你無法產生論文PDF出來.

**Comment by loveakai** [comment]
![2016-05-12 12 39 53](https://cloud.githubusercontent.com/assets/18327156/15204319/a1c29a04-183e-11e6-8318-c9e7c97b7c46.png)

左邊是1.3.2版產出的論文，右邊是1.4.0版。可以看出本文跟item之間的空隙不見了，但本文跟item內的行距仍不同。
字型的話我覺得沒什麼改變，但也可能是我對字型眼盲。您之前的變更說明好像說字型有改用新的package，不過我也看不出差異。

**Comment by wengan-li** [comment]
因為我在研究哪些code是沒用,
所以我刪到那邊的空間了.
但因為我的內容跟你的內容不一樣,
所以有些地方可能用你的內容會非常明顯,
但我的卻是差不多.

我先給你解決方式,
之後我會下一版修正這問題.
你在'ncku/configure.tex'中
在'\usepackage{enumitem}'前面,
插入這一句'\setlength{\parskip}{0.3cm}'
應該就變回你要的效果.

**Comment by loveakai** [comment]
您好，加入那一行後本文與item之間的間距回來了。
不過item內的跟原來似乎差不多。
![2016-05-12 16 08 49](https://cloud.githubusercontent.com/assets/18327156/15207981/ea31777a-185b-11e6-9873-9a5e5d1f28a0.png)

**Comment by wengan-li** [comment]
請問你把'\setlist{noitemsep, nosep}'改成'\setlist{nosep}'後,
是你要的效果嗎 ?

因為在我那邊好像看不出差別.

**Comment by loveakai** [comment]
不是耶，我覺得好像沒什麼變化。

**Comment by loveakai** [comment]
我可以用了，但我不知道是改到什麼耶@@
就原始碼來說應該是沒有改東西，但我有改前後文的一些內容。
不過就結果來說是可以用了，謝謝您。

**Comment by wengan-li** [comment]
所以我才說那個東西有點煩呢

請問你現在最後版本
你用了什麼 ?
a. '\setlength{\parskip}{0.3cm}'
b. '\setlist{noitemsep, nosep}'
c. '\setlist{nosep}'
讓我知道一下你的設定以讓我思考怎改它.

**Comment by loveakai** [comment]
我最後只有用c而已，a的話會在本文跟item之間產生過大的間隙，b跟c在我的論文裡面好像沒有差別。最終結果如下圖。

![2016-05-12 20 01 41](https://cloud.githubusercontent.com/assets/18327156/15213846/4bfb00c8-187c-11e6-97fc-ab0722d09e6e.png)

**Comment by wengan-li** [comment]
你有沒有興趣試一下使用a,
去調整一個你覺得不錯的間隙嗎 ?
由0.3cm, 0.2, 0.1慢慢調整.
我覺得你這一頁很適合改這個東西.

**Comment by wengan-li** [comment]
我重新研究一下
發現這個效果原來的確做`c.`就可了.
![dev-item](https://cloud.githubusercontent.com/assets/6211564/15074315/da3dd26c-13d0-11e6-9a40-77c606e604b1.png)

**Comment by loveakai** [comment]
a的那個東西應該是在決定本文跟item中間的距離吧，我自己試了一下覺得大概是0或0.1比較好，0的話就是item跟本文中間的行距跟本文跟本文之間是一樣的，0.1的話是有一點若有似無的間距，視覺上可以提示讀者item已經結束要進入本文了。
我個人認為可以保留a的選項讓使用者調整，畢竟每個人的指導教授偏好不同......

**Comment by wengan-li** [comment]
今天的實驗, 去掉`\setlist{noitemsep, nosep}`,
再試用一些package去調內容的位置.
好像比較好了.
你覺得呢 ?

![diff](https://cloud.githubusercontent.com/assets/6211564/15265650/eae850f0-19bc-11e6-85dc-61a4aafcc664.png)

**Comment by loveakai** [comment]
我個人是覺得左邊看起來好像比較密集，然後本文跟item之間有較寬的間隙，但item之間的行距沒有加寬（類似於段落之間的距離的感覺）。右邊的話則是item之間的的間距也加寬了，如果每一點item內容都是短句的話，整篇看起來會比較空。但如果是長段落的話可能有助於閱讀。
我自己的話是比較喜歡左邊的，因為我覺得不會有很頻繁的留白寬度的切換，至於item因為前面已經有標號了，所以似乎不需要再調整留白寬度提示讀者換段。只需要在本文進到item的時候有些許留白，提示讀者要進入item了就好。

**Comment by wengan-li** [comment]
理解 我去調整有關'本文進到item'的部份

**Comment by loveakai** [comment]
還是說有什麼地方可以簡單的設定段距（不是行距），同時也可以apply到item之間，讓喜歡的人自己選擇呢？

**Comment by wengan-li** [comment]
是有相關的功能, 但我還在理解那些API,
因為有時候我以為這只會影響部份的地方 (如: '本文進到item'),
但結果發現都同時影響 item跟item之間 的部份, 我要再弄弄就是了.

之後會提供出來的.

**Comment by loveakai** [comment]
我剛看了一下[成大碩博士撰寫論文須知](http://www.cc.ncku.edu.tw/rule/content.php?sn=684)，裡面並沒有針對段距做要求。而在英文延伸摘要撰寫格式說明中則是要求段落是單行間距，你覺得是不是比照英文格式，統一段落單行間距呢？[這邊有範例](http://www.phys.ncku.edu.tw/phys/GradThesis.pdf)

**Comment by wengan-li** [comment]
聽你說完後
試驗一下就發現滿驚人的感覺.
左邊 1.4.0版
中間 改用單行間距
右邊 單行間距 + `\setlist{nosep}`

感覺中間超不錯的感覺.

![diff2](https://cloud.githubusercontent.com/assets/6211564/15265917/0fd7a452-19c6-11e6-9ded-b00d63fe7b27.png)

**Comment by loveakai** [comment]
我覺得中間的確實比較好，看起來有提示理解的效果，中間的之後看似行距減少了，當全部都是內文沒有item時，不知道看起來會不會都很密集（在紙本上可能感覺會更明顯，但可能要視情況而定）。
另外我剛剛有試著用`\\`加空一行來控制間隔，結果實在是有夠難改的，所以就當我沒講過這提議吧，還是在設定那邊就寫好比較明智
剛剛我又發現另一個問題，在你的說明文件裡面應該比較不會發生的，是一般來說中文在本文段落開頭是空兩格，但是在某些自動會起新段落的地方，預設下一行縮排（例如`\StartSection{.}`之後），但該縮排並非兩個全形字元。不知道這部分有沒有什麼解決方式？
在其他的段落我是直接用打兩個全形空白來做到的，但是如果在上述地方也加入兩個空白，會造成那一行有預設的縮排＋兩個全形空白這樣的距離，導致全文的縮排沒有辦法統一。

ps.建議將`\usepackage{hyperref}`改成`\usepackage[colorlinks,linkcolor=black,anchorcolor=black,citecolor=black]{hyperref}`，這樣引用那邊就不會有那個綠綠的框。

**Comment by wengan-li** [comment]
你如果看中間那個,
我用了`\usepackage{parskip}`,
原本會全部每一段會自己縮一些空格,
變成完全沒有縮進去.
這樣的話,
再加你的2個全形空白, 應該會沒問題.
你可以試試看.
但在英文的話,
不知道這樣做有沒有什麼問題.

對我這種眼殘的人來講,
我反而覺得那些框框滿好看.
但你這樣提到,
我可能另加可自行設定要不要好了.

**Comment by loveakai** [comment]
我還沒寫到英文摘要的部分，在latex裡面半形空白應該是視為沒有東西，所以英文的話之後可能也要以全形空白來調整縮排吧。

那些框在編輯的時候應該沒什麼問題，不過在列印紙本以及繳交電子全文給圖書館時是要拿掉的吧。

**Comment by wengan-li** [comment]
那你就不用擔心
列印紙本那個框框是不存在的
但電子版就會保留就是了.

不用擔心,
在你之前已經有一些同學 (人數不詳, 起碼4~5位以上) 用了這模版交了 (包括我),
只是應該你是第一位全中文 (其實有另一位#5 , 但沒下文).

我可以跟你說
圖書館超級不會管這些東西.
他們其實連內容的行距其實都不太管,
之前模版的內頁邊界錯了, 他們根本都沒看.

只要`封面`, `考試合格證明`, `論文內容次序`存在而且正確,
就會99%會收的.
餘下1%就是對PDF有沒有上鎖, 填內容, 在網頁填論文資料,
都有做就OK的了.

重點還是你的內容有沒有做到你自己的要求,
老師和口試委員的要求,
畢業論文就這樣而已呢.

**Comment by loveakai** [comment]
瞭解了。
對我來說，只要latex可以順利compile就好了，格式上基本上沒什麼要求的。
要求的當然是 ---消音---
謝謝你願意幫我改這麼多，不然我還真想偷偷用word寫論文......

**Comment by wengan-li** [comment]
如果你還是要想word來做,
我還是能十分理解的呢.
的確有些是word比較方便.

**Comment by wengan-li** [comment]
[請更新模版到v1.4.1](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.4.1), 你主要把'ncku'資料夾更新則可.
推薦你去讀一下[ChangeLog](https://github.com/wengan-li/ncku-thesis-template-latex/blob/master/ChangeLog.md)看看由v1.4.0到v1.4.1有沒有對你有什麼影響.
直接刪除來更新`ncku`都可的.
但比較推薦你研究新的`conf.tex`, 因為這次對這檔案有些修改.

由於你是使用中文來編寫, 請在`conf.tex`中使用`ThesisWroteInChi`.

請試新的東西看看, 告訴一下你覺得如何.

**Comment by loveakai** [comment]
嗨！
謝謝你提供新的版本。
我目前看到的問題是，已經可以用中文設定格式了，不過它似乎會從零開始，另外是它也只有零，這是我覺得比較怪的。
![2016-05-21 12 48 11](https://cloud.githubusercontent.com/assets/18327156/15446402/89b0fdfa-1f52-11e6-8fbe-e9e5d25ef42f.png)

另外想請教一個問題，雖然不一定會用到。如果我想要調全文的行距要在什麼地方設定呢？我不太確定等我寫完之後，我老闆會希望我使用多大的行距。

**Comment by wengan-li** [comment]
1.
'零'的問題已在[v1.4.3](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.4.3)修正了, 更新模版到v1.4.3, 把'ncku'資料夾更新則可.

2.
唔..你問到我的痛處了.
我個人其實都沒有很懂行距的設定.
因為模版的格式是由陳朝鈞老師的版本進行了大量的修改,
到現在`ncku/style/ncku.sty`還是有微量當時留下來的設定是我不懂的.
其他我懂的都有經過修改或拿掉.

你要去研究
```
1. `ncku/style/ncku.sty`中的`\doublespacing`和`\singlespacing`
2. `ncku/command/cmd-spacing.tex`中`\UseEngLinesSpacing`和`\UseChiLinesSpacing`

`\doublespace`和`\singlespace`是Latex原生的行距設定.

我故意在`\UseEngLinesSpacing`和`\UseChiLinesSpacing`是先做舊模版設定, 再強制做Latex原生的行距, 以強制使用Latex預設的行距.
```

假如你在`conf.tex`有使用`\ThesisWroteInChi`, 那你只要修改`\UseChiLinesSpacing`中的那部份.

你只要插入一句`\baselineskip=xxx pt`則可 (可參考`ncku/style/ncku.sty`中的`\doublespacing`或`\singlespacing`的寫法).
但如果你發現沒效, 推薦直接修改`\doublespacing`或`\singlespacing`的值.


把以上的話簡單化
```
就是請到`ncku/command/cmd-spacing.tex`中的`\UseChiLinesSpacing`最下面插入一句`\baselineskip=xxx pt`則可.
```

**Comment by loveakai** [comment]
您好，
嘗試後發現，第一次編譯的時候可以正常編譯，但因為citation部分無法正常產出須多編譯幾次，即會產生下列error。若將中間產出的檔案刪除後又會可以編譯但citation有錯誤，而一但有已存在的中間檔案，就無法編譯。
![2016-05-22 18 24 49](https://cloud.githubusercontent.com/assets/18327156/15453507/fc772424-204a-11e6-92bf-c6bcca264e2e.png)

至於行距的部分我尚未嘗試。

**Comment by loveakai** [comment]
我好像知道問題出在哪裡了
我設定的是章名稱是
一
節名稱是
（一）
然後在設定那邊是用
`\SectionTitleNumFormat{%
  （\StyleSNumChiNum）}`
就不行了
應該是那個括號的關係
這個有辦法處理嗎＠＠

**Comment by wengan-li** [comment]
我未試過括號, 所以我都不肯定.

你可能要試試看:
```
1. \SectionTitleNumFormat{(\StyleSNumChiNum)}
2. \SectionTitleNumFormat{( \StyleSNumChiNum )}
3. \SectionTitleNumFormat{\( \StyleSNumChiNum \)}
4. \SectionTitleNumFormat{\textparenleft\StyleSNumChiNum\textparenright}
5. \SectionTitleNumFormat{\textparenleft \StyleSNumChiNum \textparenright}
6. \SectionTitleNumFormat{$($ \StyleSNumChiNum $)$}
7. \SectionTitleNumFormat{（\StyleSNumChiNum）}
```
這幾個情況哪個能work.

Latex有些位置是不能使用某些字之類,
某些command不能連到字之類,
所以都要靠試哪種才能用.

**Comment by wengan-li** [comment]
有關之前你提過的想自定行距, 請參考`v1.4.4`中的`\SetLineStretch`.

**Comment by loveakai** [comment]
謝謝，我已經試用過這功能了，可以正常使用。
另，新的控制指令`\section`和`\subsection`的部分，是不是沒有預設會另起新段呢？
我目前是在這兩個指令前都加入一行空行來解決，若有空行的話就可以正常顯示新段了。

**Comment by wengan-li** [comment]
呀....\section和\subsection不算新的command..
那個你還是請使用\StartSection和\StartSubSection

我不懂你的問題.
何為'另起新段' ??
是說希望有比較大的空白在Section的題目前面是嗎 ?

**Comment by loveakai** [comment]
難以用言語形容，看圖可能會比較清楚。在`\StartSection`前如果沒有`\\`符號或空行的話，標題會接續在前段後面出現。
![2016-05-27 15 17 12](https://cloud.githubusercontent.com/assets/18327156/15600996/11209eae-2420-11e6-96bd-50c1eb4f2052.png)

**Comment by wengan-li** [comment]
請更新`v1.4.5`,
已修正沒有`\\\\`符號或空行標題會接續在前段後面出現的問題.

**Comment by wengan-li** [comment]
還有在[之前提到的](https://github.com/wengan-li/ncku-thesis-template-latex/issues/10#issuecomment-220825581)
`\SectionTitleNumFormat{ （\StyleSNumChiNum ）}`
由於`v1.4.5`中已不再提供`\SectionTitleNumFormat`

請改使用
`\SetNumberingFormat`
```
\SetNumberingFormat[Section]{
  BeginText = {（}, EndText = {）},
  CNumStyle = {}, SNumStyle = {ChiNum},
  SepBetweenCnS = {},
} % End of \SetNumberingFormat{}
```
這個寫法.

**Comment by loveakai** [comment]
您好，我已改用新的寫法。不過似乎又會出現在equation時希望可以用數字呈現，之前1.4.4版似乎已修正這問題，但在1.5.5版又出現了。
![2016-06-06 22 49 02](https://cloud.githubusercontent.com/assets/18327156/15826261/792267e6-2c39-11e6-9667-cdd9b5b4c8cf.png)

**Comment by wengan-li** [comment]
我已更新成`1.4.6`, 應已修正你這問題.
請看看如何.

**Comment by loveakai** [comment]
您好，謝謝您的更新，目前的版本已可供我最近的需求，謝謝您。
