### ISSUE TITLE
使用全型標點符號引用

### ISSUE THREAD

**Issue by loveakai** [wengan-li/ncku-thesis-template-latex#11]
您好，上次感謝您的協助讓我可以使用apa格式引用文獻。但是利用這個方法做出的引用格式括號會是半形，想請問有沒有辦法手動強制全型呢？
我在網路上有找到這個一個叫做natbib的package的說明，在此package中需要使用
\usepackage[option]{natbib}後，可以用
\bibpunct{（}{）}{；}{a}{，}{;}
這樣的方式做出類似apa的引用格式，在插入引用時只要使用
\citep{}就可以做出類似apa的引用格式(但標點是全型)

我自己試圖修改了一下，發現似乎是\BibUse****這一行中沒有類似\BibUseNatbib這一行的選項，導致我即使在前面加入
\usepackage{natbib}
\bibpunct{（}{）}{；}{a}{，}{;}
這兩行後也還是會呈現error。

不曉得針對這種中文撰寫，需要全文使用全形標點(或至少引用的部分)的需求您有沒有什麼建議？
謝謝，感激不盡！

**Comment by wengan-li** [comment]
針對你的問題,
我是研究出應該能符合你要求的做法.

\BibUse***那邊是提供幾個基本的bib style, 那不是你要的東西.

你要做的是:
```
1. 在'ncku/configure.tex'中,
    在'\usepackage{fontspec}'下一行插入'\usepackage[utf8]{inputenc}',
    以讓你的全形能使用.

2. 在'ncku/configure.tex'最後面,
    插入'\usepackage{natbib}'和'\setcitestyle{open={（},close={）}}',
    用\setcitestyle來設定你的全形吧.
    (有關\setcitestyle的說明,
     請參考https://www.sharelatex.com/learn/Natbib_citation_styles)

3. 你做完後, 推薦先把'*.aux'和'*.bib'的檔案先刪一次,
    之後再rebuild (XeLaTex -> BibTex -> XeLaTex),
    如有什麼問題, 做幾次BibTex去更新.bib檔,
    那再回去做XeLaTex應該就會ok的.
    (起碼我是試過直接rebuild .bib檔幾次就行了)
```

針對未來模版內文能否使用半形全形,
我現在預計會在下一版時增加'\usepackage[utf8]{inputenc}'來令.tex能直接輸入半形全形,
以讓同學們在內文中能打半形就顯示半形, 全形就顯示全形,
但是否會100% OK則是未來值得再討論的問題. 

而引用的部分是否真的有全形的需求,
這要更多的同學回報了,
否則我預定是不會把它做全形的設定.

**Comment by loveakai** [comment]
您好，謝謝您的回覆，我仍然無法使用。

想請問您提的這個解決方案，在\BibUse***這邊，要做什麼設定呢？

在natbib這個package中， 如果內文使用\citep{}這樣的指令，在不使用\usecitestype指令的情況下，預設應是Jones et al. (1990) 這樣的型式，但我在預設的\BibUseAbbrv，或是全部%掉，結果都會是abbrv的格式i.g. [1]。所以我在想說會不會是在哪邊有預設引用格式為abbrv？導致於在conf/conf.tex中不管怎麼設定，都會是abbrv格式引用？

謝謝。

**Comment by wengan-li** [comment]
因為你說你要用apa
所以要使用BibStyleUseApacite

由於預設是使用abbrv
只是你不使用任何或BibStyleUseApacite去取代
便會自動使用BibUseAbbrv

你要先確定使用BibStyleUseApacite後是apa格式
才再加package natbib到'ncku/configure.tex'

**Comment by loveakai** [comment]
您好，您一開始說的方法是對的，是我操作上的錯誤導致不能用。
簡單而言操作流程如下（供APA中文引用同學參考）

1. 同上面指令設定全形
2. 於`conf/conf.tex`中設定`\BibStyleUseApacite`
3. 於`ncku/configure.tex`中在`\usepackage{fontspec}`下一行插入`\usepackage[utf8]{inputenc}`
4. 在`ncku/configure.tex`最後面，插入`\usepackage{natbib}`，再插入格式設定的code<br>
**注意：一定要在最後面插入，我就是因為放在前面所以不能跑**
5. 至於全形格式設定的部分可以用wengan-li 大說的用`\setcitestyle{open={（},close={）}}`<br>不過我個人因為需要連中間的逗點都全形，所以我使用的是`\bibpunct{（}{）}{；}{a}{，}{;}`

註：我使用的環境為win7/MikTex/Texmaker

**Comment by wengan-li** [comment]
所以這邊應該解決了 ?
我先關掉, 需要的話你再開就好了
