### ISSUE TITLE
引用章節由第1章－>第一章

### ISSUE THREAD

**Issue by ujmyhn** [wengan-li/ncku-thesis-template-latex#12]
您好，感謝您熱心分享這個模板!
有個問題想要請您協助，
1.關於使用\ref{chapter:review}，會顯示為第"2"章，我該如何改為第"二"章，讓他和章節的標題符合呢?
－>使用v1.4.3已經沒有這個問題!

2.可以將附錄的節標題由"6.1"改為"A.1"嗎?
![image](https://cloud.githubusercontent.com/assets/19511869/15452049/e455854e-2012-11e6-8252-fa959a8a293f.png)

3.希望表格可以不要加白底，不知道該如何更動設計?

4.Table 二.1－> 表 2.1
![image](https://cloud.githubusercontent.com/assets/19511869/15452458/a29ada64-2021-11e6-8c8b-26a0a09d154d.png)

5.第B章－> 附錄B
![image](https://cloud.githubusercontent.com/assets/19511869/15452466/ee6dfc5a-2021-11e6-8f8e-d9edaf3fd437.png)

謝謝!

**Comment by wengan-li** [comment]
1~3:
  看起來我要新增這些功能, 故我需要一些時間.

4:
  你有看到第2行的error嗎 ?

  'l3-too-old'即是你要更新MikTex, 請參考[模版說明文件的'3.3.3 更新MiKTeX'章節](https://github.com/wengan-li/ncku-thesis-template-latex-sample/blob/master/thesis%20(demo).pdf), 這情況在[版本v1.4.1](https://github.com/wengan-li/ncku-thesis-template-latex/blob/master/ChangeLog.md)時提到.

**Comment by loveakai** [comment]
我也有類似4的問題，不知道在算式的部分有沒有辦法是(1.1)而不是(一.1)
![2016-05-22 18 43 50](https://cloud.githubusercontent.com/assets/18327156/15453565/3e6991ee-204d-11e6-9ee7-bc753d5e5a43.png)

**Comment by wengan-li** [comment]
@ujmhn
請更新到`v1.4.4`.
2. 已修正這錯誤
3. 請參考新版的中Figure/Table的`opacity`這個設定.
4. 請參考新版的`\SetCustomTableName`這個設定.
5. 請參考新版的`\AppendixChapterTitleNumFormat`這個設定.

請注意`v1.4.4`可能會影響到你原本`\ChapterTitleNumFormat`的設定, 請看新的用法.

**Comment by wengan-li** [comment]
@loveakai
請更新到`v1.4.4`, 這問題應能修正.

同樣請注意`v1.4.4`可能會影響到你原本`\ChapterTitleNumFormat`的設定, 請看新的用法.

**Comment by ujmyhn** [comment]
真的感謝您費心修正!
使用v1.4.4真的改善了許多問題!

不過還有幾個小問題想要請教，
1. 關於使用\ref{chapter:review}，會顯示為第"2"章，我該如何改為第"二"章，讓他和章節的標題符合呢?
    在v1.4.3已經沒有這個問題，但v1.4.4不會顯示為中文字

2.中文版的目錄：第一章.－>第一章，可以把點去掉嗎?

抱歉，我又要來麻煩您!

**Comment by loveakai** [comment]
@wengan-li 
你好，算式的問題已經修正了。
想請問章節的部分，原本會顯示「第一章」這樣的，現在只會顯示「一」這樣是正常的嗎？謝謝！

**Comment by wengan-li** [comment]
@loveakai
請注意v1.4.4的`conf.tex`中\ChapterTitleNumFormat新的使用方式.
我把那個完全改成能由你自己決定那邊是顯示什麼.

**Comment by loveakai** [comment]
@wengan-li 我看到了，之前沒注意，謝謝！

**Comment by wengan-li** [comment]
@ujmyhn
1.
我研究了4~5天才發現原來`v1.4.4`改出來的`\ChapterTitleNumFormat`, 沒法修改你這個問題,
我只好重新設計這個功能, 並我推薦改使用新的`\SetNumberingFormat[...]{ ... }`.
請參考新的說明文件中章節`3.4 論文基本資料設定: 16. 章節標題的設定`.

2.
請使用
```
\SetNumberingFormat[ ... ]{
  ...
  SepAtIndex = {},
  ...
}
```
這個使用方式.

@loveakai
抱歉, 請改使用`\SetNumberingFormat[...]{ ... }`,
有關修改方式我已寫在`conf.tex`中.

@2位
極度抱歉, 新改版會大大的影響到2位, 但我發現這修改方式對未來一些新增和修改比較好.

**Comment by ujmyhn** [comment]
謝謝您的幫忙! 
不過我又有問題想請您幫忙...

在生成reference時需要
![image](https://cloud.githubusercontent.com/assets/19511869/15818941/cfd5721c-2c12-11e6-80bf-4e8d1e4c453f.png)

使用\BibStyleUseApacite

![image](https://cloud.githubusercontent.com/assets/19511869/15819028/4548433a-2c13-11e6-978d-77a78b186446.png)

變成沒有編號又會有縮排，不知道這個問題有沒有方法可解?

**Comment by wengan-li** [comment]
@ujmyhn

唔..
我覺得你誤會了一些東西
`\BibStyleUseApacite`是在[Issue #9](https://github.com/wengan-li/ncku-thesis-template-latex/issues/9)時提出的.

但根據我理解你這邊的問題,
你應該是要有一個數字或一個名字顯示在Reference那邊每一個item前面.

但是使用package<apacite>做出的Apacite format **原本就是這樣的**.
請參考[這邊](https://www.overleaf.com/latex/examples/package-example-apacite/jkssmfcpzwmy#.V1Zks7MXHmE).

或是你可能是想要另一種的APA format, 那叫`apalike`.
請參考[這邊](https://www.sharelatex.com/learn/Bibtex_bibliography_styles).
這個選項模版暫未提供.

所以不知道有沒有解決你的問題呢 ?

**Comment by ujmyhn** [comment]
詢問過系上以後，發現`\BibStyleUseApacite`所跑出來的格式是可以被接受的!

本來以為每篇文獻前面都需要加註編號的...

所以這樣就沒問題了! 再次感謝您耐心的回覆問題!

**Comment by wengan-li** [comment]
我覺得你個人接受不了就考慮改用apalike,
當然都要再去問問系上.

**Comment by wengan-li** [comment]
@ujmyhn
你可用`v1.4.6`改使用`\SetupReference`去使用apalike看看效果如何.

**Comment by ujmyhn** [comment]
之前的問題都有解決感謝您的幫忙！
不過因為系上要求中文摘要的關鍵字必須要是全型標點符號...
目前的格式是半形的逗號！不知道這個問題是不是有辦法調整?

**Comment by wengan-li** [comment]
@ujmyhn
這個需要直接修改底層LaTex的寫法.

請去`ncku\command\cmd-keyword.tex`,
修改第57~64行中
把 '`{\VarAbstractChiKeywords}{,`' 改成 '`{\VarAbstractChiKeywords}{，`' 應則可.

**Comment by ujmyhn** [comment]
感謝所有您的幫忙，論文才能這麼快的進入尾聲，不用為了格式而煩惱!

最後再檢查頁碼和目錄時，發現一個小問題，英文延伸摘要的標題頁無法顯示頁碼!

不知道這個部份能否再麻煩您協助? 謝謝您!

**Comment by wengan-li** [comment]
學校沒有訂出英文延伸摘要其實要不要頁碼,
所以我已寄信給圖書館查問,
等待明天的回應吧.

你急需的話, 請到 `ncku\command\cmd-abstract-extended.tex`.

如想顯示頁碼:
修改第47行: `%\thispagestyle{empty}%` 和第88行: `%\pagestyle{plain}%`

如不想顯示頁碼:
修改第47行: `\pagestyle{empty}%`

**Comment by wengan-li** [comment]
我已更新成`1.4.7`, 已修正你這問題.
請看看如何.

**Comment by spotdy** [comment]
你好
藉由上面問題想請問你
我在論文審查時，遇到問題
可否再請你幫忙
圖書館說 "羅馬數字頁碼:請從"中文摘要"自「i」開始編頁碼，"
而我的是從「iii」開始編碼
麻煩你了
謝謝

**Comment by wengan-li** [comment]
@spotdy 
極度抱歉, 想不到圖書館突然說這一回事.
請更新到v1.4.8, 這問題已修正.
