### ISSUE TITLE
節置中

### ISSUE THREAD

**Issue by loveakai** [wengan-li/ncku-thesis-template-latex#13]
您好，想請教一個問題。
想請問是否有辦法在哪個地方調整，讓節可以置中呢？
例如以下圖這樣
![2016-06-01 15 15 37](https://cloud.githubusercontent.com/assets/18327156/15701383/83fb799a-280c-11e6-9ef8-45e0e4920088.png)

**Comment by wengan-li** [comment]
嗯~
有趣的想法, 但`v1.4.4`還未能提供呢.
我在新一版提供這個設定.

**Comment by wengan-li** [comment]
請參考`v1.4.5`的`\SetNumberingFormat`中的TextAlign設定, 看這個有沒有令你滿意.

**Comment by loveakai** [comment]
您好，謝謝，我喜歡這個設定方法。
另外想請問章節的字體大小是否是可以改的呢？

**Comment by wengan-li** [comment]
這真的沒有在預期的功能設定中.

如果你想自行修改
你可到`ncku/command/cmd-chapter.tex`中的
找`\DisplayXXXXXHeader`, 例如 `\DisplaySectionHeader`
修改在第189,192行 這2行前面加入你要的字型大小,
如`\Large`之類.
(可參考`\DisplayChapterHeader`)

你覺得這功能十分需要 ?

**Comment by loveakai** [comment]
謝謝，我覺得這個功能不需放在模版中，只是我個人需要修改而已。因為其他人未必有這個需求，只是我老闆有提到要改字體大小這部分這樣。

**Comment by loveakai** [comment]
您好，請問在1.4.6版中若要修改節的字體大小的話，也是在同樣的地方修改嗎？我今日試圖修改1.4.6版的相對位置（144-146），但似乎沒什麼反應。我的寫法如下
\ifthenelse{\equal{#1}{\empty}}%
  {%
    \parindent  0pt \large \textbf{#2} \par%
  }%
  {%
    \textbf{#1\hspace{0.5cm}#2} \par%
  }%

**Comment by wengan-li** [comment]
嗯~
我不知道你做錯什麼,
但你的code我看不到任何設定字體大小的command.
這邊提供你考慮.

方法1: 2行都寫
```
{%
  \LARGE \parindent 0pt \textbf{#2} \par%
}%
{%
  \LARGE \textbf{#1\hspace{0.5cm}#2} \par%
}%
```

方法2: 寫在\ifthenelse上面, 不用擔心影響到內文, 因為上下有一個environment block包住.
```
\LARGE
\ifthenelse{\equal{#1}{\empty}}%
{%
  \parindent 0pt \textbf{#2} \par%
}%
{%
  \textbf{#1\hspace{0.5cm}#2} \par%
}%
```

**Comment by loveakai** [comment]
你好
應該是我誤解了你的意思
我以為字形是加在`\parindent 0pt \large \textbf{#2} \par%`這行
裡面的`\large`就是我錯加進去以為會有效果的指令
而且在之前的版本這樣是可以的
應該是因為我對這邊的語法不熟悉的關係
謝謝您的建議
我已經用方法2解決了

**Comment by wengan-li** [comment]
呀~
我眼殘沒看到那個`\large`.

嗯 那我猜應該是沒太明顯而沒發現有改變而已,
可參考[這邊的Reference guide](https://www.sharelatex.com/learn/Font_sizes,_families,_and_styles).
`\large`跟`\normalsize`其實要單獨有對比才會比較明顯, 大量文字下可能沒發現有變.
而你可參考第30~32行的chapter寫法是使用`\Large`, 所以比較明顯.
