### ISSUE TITLE
參考文獻的問題

### ISSUE THREAD

**Issue by spotdy** [wengan-li/ncku-thesis-template-latex#14]
您好 
我遇到了關於參考文獻的問題，想詢問您
1.我在用apa 格式 引用為中文參考資料時
所出現如下:
林志六、葉嘉新. (2008). 新藥開發與臨床試驗. 秀威資訊科技.
如果我希望出現的格式是: 
張保隆、陳文賢、蔣明晃、姜齊、盧昆宏、王瑞琛（2000)。生產管理。台北市：華泰文化。
就是如何設定可以把.換成。在參考資料為中文時

2.我引用是書籍時，如何設定可以出現出版社地點?

謝謝您的協助!!

**Comment by wengan-li** [comment]
嗯~
我不知道能否使用apa來顯示地點呢,
我現在在測時都不顯示出來.

不知道你有沒有一些例子包括了地點能給我看呢 ?
我要一些時間研究這問題.

**Comment by spotdy** [comment]
像是這個樣子
Gumby, T. F. (1972). The brain specialist. Cambridge, England: 
Python.
謝謝你

**Comment by wengan-li** [comment]
嗯..
好像你誤會我的意思了.

我是說你手上有沒有一些完全符合你要求的參考文獻格式的實體例子,
例如有一本真正的書, 一份paper 之類實體類的東西是這樣顯示 ?

否則我在思考這是非一般的工具能提供,
可能要由另一方式來處理.

**Comment by wengan-li** [comment]
[請參考這個網頁](https://verbosus.com/bibtex-style-examples.html), 雖未包括`apacite`.
但不知道有沒有包含到你想要的格式呢 ?

而且你說的`apa`是指哪種的format呢 ?
是使用`apacite`還是`apalink` ?

**Comment by wengan-li** [comment]
我研究了好幾天, 我發現還是沒法有好方法能解決[你的1.問題](https://github.com/wengan-li/ncku-thesis-template-latex/issues/14#issue-160338027).

我發現直接使用正常使用LaTex是沒法解決你這個問題, 但是如果你直接修改`thesis.bbl`則能解決你問題, 你要記得`thesis.bbl`是每次你更新bib時都會更新, 所以你應只修改最後一次.

你打開`thesis.bbl`, 找出你想修改的那個文獻的label, 你應該會找到一個像 '` \APACrefYear{2011}. `' 的年份 (前提是如果你在`\SetupReference`是使用`apacite`), 你改成 '` \APACrefYear{2011}。 `', 應能解決你的問題.

而2.我倒是有方法, 就是使用一些轉變的做法, 就是**不正式**的填Bibtex的資料.
用你的例子, 用這方法來填.
```
@book{bib:lateb,
  author={\textnormal{張保隆、陳文賢、蔣明晃、姜齊、盧昆宏、王瑞琛}},
  publisher={\textit{生產管理}. \textnormal{台北市：華泰文化}.},
  year = {2000},
}
```

應該就能生出
```
張保隆、陳文賢、蔣明晃、姜齊、盧昆宏、王瑞琛（2000). 生產管理. 台北市：華泰文化.
```
這種效果.

**Comment by spotdy** [comment]
好 謝謝你的回覆
