### ISSUE TITLE
回饋

### ISSUE THREAD

**Issue by loveakai** [wengan-li/ncku-thesis-template-latex#18]
您好：
謝謝您的幫助，日前我已順利繳交論文並畢業。
我在審查論文時遇到一些錯誤，在此提出來，期待能對後來的同學和學弟妹有所幫助。
我遇到的錯誤有兩個，第一個是封面的月份。

> 
> % --- Date 日期 ---
> 
> % 依本校研究生學位考試細則第十條規定：
> %
> % 碩士班:
> %   論文日期：上學期為〇〇〇年1月；下學期為〇〇〇年6月，以該學期結束日期(一月或六月)為準。
> %   (如：在上學期101年9月~102年1月期間口試，
> %       不論是在此期間何月份口試，其日期均固定為102年1月).
> %   另碩士生如101上學期完成口試，101下學期申請出國，102上學期辦理離校，
> %   則論文封面為103年1月

我的口試是7月，我的設定是6月，不過圖書館說封面的日期是要等於或晚於口試日期的，因此我後來改成7月就過了。

第二個錯誤是英文延伸摘要的部分，他說我沒有浮水印。
事實上是有的，但是因為summary那個框框似乎會生成一個半透明的白底，導致浮水印比其他頁淡，因此圖書館員誤判。因為我使用的adobe acrobat是具有編輯效果的，所以直接刪掉那個白底就好了。但其他人如果無法編輯pdf的話可能這方面就要想辦法處理，或許打電話去跟圖書館argue就好了。

謝謝學長提供這個模板給大家使用，因為我後來並無寫謝誌，因此在這邊表達我的感激之意，也祝各位同學與學弟妹都能順利畢業，鵬程萬里！

**Comment by wengan-li** [comment]
恭喜你已交出論文, 即是可以說已經是99%畢業了.
在此先祝你能畢業後, 能找出最適合自己的生活方式 (包括工作, 生活, 跟身邊的人的關係等),
我覺得那是人生最重要的事項.

---------------------------------

感謝回饋過程和結局.

真的奇怪, 那明明是規定...
但它的說明跟圖書館講的都不算有錯,
"101上學期完成口試 ... 102上學期辦理離校, 則論文封面為103年1月"
都算是 "封面的日期是要等於或晚於口試日期",
但圖書館講的明確很多.
這情況我會補回`conf.tex`中.

理解, 
其實所有的figure/table 跟那個summary都是會有透明以不用擔心蓋到浮水印.
但看起來即是浮水印太淡了.
那我把那邊預設的透明值調回高一點好了.

謝謝你的回報.
