### ISSUE TITLE
Dissertation Format

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#19]
I just realize that all chapters should be formatted in indent paragraph? 
Because as far as I know, we just use \noindent paragraph? 

How can I change from noindent paragraph to indent paragraph from new paragraph from previous one?

Thanks a lot your help!

**Comment by wengan-li** [comment]
If you want all paragraph as indent paragraph,
comment the following command in configure.tex:
```
%\usepackage{parskip}
```
and append command:
```
\usepackage{indentfirst}
```
I hope this is what you want.


Here is the example:
![example-indent](https://cloud.githubusercontent.com/assets/6211564/18675770/085fb766-7f86-11e6-98d5-ca480b1bbcba.png)
