### ISSUE TITLE
Adding definition, theorem and lemma

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#20]
Hi, I was working my dissertation and I need some definition, theorem, and so on.

Then I added some codes to the ncku\configure.tex:
\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{proposition}[theorem]{Proposition}
\newtheorem{corollary}[theorem]{Corollary}

\newenvironment{proof}[1][Proof]{\begin{trivlist}
\item[\hskip \labelsep {\bfseries #1}]}{\end{trivlist}}
\newenvironment{definition}[1][Definition]{\begin{trivlist}
\item[\hskip \labelsep {\bfseries #1}]}{\end{trivlist}}
\newenvironment{example}[1][Example]{\begin{trivlist}
\item[\hskip \labelsep {\bfseries #1}]}{\end{trivlist}}
\newenvironment{remark}[1][Remark]{\begin{trivlist}
\item[\hskip \labelsep {\bfseries #1}]}{\end{trivlist}}

\newcommand{\qed}{\nobreak \ifvmode \relax \else
      \ifdim\lastskip<1.5em \hskip-\lastskip
      \hskip1.5em plus0em minus0.5em \fi \nobreak
      \vrule height0.75em width0.5em depth0.25em\fi}

 As follows: 
![add_codes](https://cloud.githubusercontent.com/assets/13177534/18735819/7794c828-80b3-11e6-9885-c076d67a93aa.JPG)

Then, I type some text:
![type_codes](https://cloud.githubusercontent.com/assets/13177534/18735828/8ae8a516-80b3-11e6-9d8a-3b65ceec1e3a.JPG)

The result is as follow:

![result_codes](https://cloud.githubusercontent.com/assets/13177534/18735836/993940f8-80b3-11e6-853e-425aee8972e2.JPG)

My point to share about this, is to ask for your help to make it more formal or fixed some necessary codes above (first Figure) so that it become available for everyone!

Best regards,

Yusie

**Comment by wengan-li** [comment]
Thanks for providing the code.
I have moved this into [TODO List](https://github.com/wengan-li/ncku-thesis-template-latex/projects/1).
I will take a look about this.

Also, although it's seem don't matter the command ordering, but I prefer this:
```
\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}{Lemma}[theorem]
\newtheorem{proposition}{Proposition}[theorem]
\newtheorem{corollary}{Corollary}[theorem]
```
Move all the counter to the right hand side which should improve the readability to suit for this format.
```
\newtheorem{ -EnvironmentName- }{ -ShowText- }[ -CounterName- ]
```

**Comment by yusie1978** [comment]
Great! 

Thanks... I hope it will become feature of the next version!!!

**Comment by wengan-li** [comment]
I have added your suggestion at v1.5.1.

Also there a little change about the file path after v1.5.x,
so if you don't need it, don't upgrade the template.
