### ISSUE TITLE
How to make subsection with new format?

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#21]
Hi, 

I have a problem with \StartSubSection command.
First, if we use the following command:
\StartSubSection{Example}{label:subsection}

then what we have is the numbers in front of "Example", e.g.:
"1.1.2 Example"

What I want to have is just like this:
"a. Example"

When I type "\StartSubSection*{a. Example}--(just like ordinary LaTeX command)--it doesn't work.

Please tell me how to solve this problem..

Regards,

Yusie

**Comment by wengan-li** [comment]
You should take a look the section `章節標題的設定` in `conf.tex`, I wrote a detail about change format of Chapter / Section / SubSection / etc.

In your case, you should use the following command:
```
\SetNumberingFormat[SubSection]{%
  BeginText = {}, EndText = {.},
  TextAlign = {Left},
  CNumStyle = {}, SNumStyle = {}, SSNumStyle = {LowerAlph},
  SepAtIndex = {.}, SepBetweenCnS = {}, SepBetweenSnSS = {},
} % End of \SetNumberingFormat{}
```

**Comment by wengan-li** [comment]
I think you should be OK right now.
Feel free to re-open this issue if you need further assistance.

**Comment by yusie1978** [comment]
Actually, i tried many time but it didn't work...

If i follow the manual reference of 章節標題的設定 in conf.tex,, the "\subsection" will be shown in TOC (table of content), but actually, I don't want it happen. 

I just want to make a simple like \subsection*{1. Example} as in ordinary latex (in which this "\subsection*{...}" will not be printed out in TOC).

Regards,

Yusie

**Comment by wengan-li** [comment]
I think I got your point.
But can you provide a example TOC of your meaning ?
I want to confirm that my understanding is correct.

**Comment by yusie1978** [comment]
Here is how i modified:
![2](https://cloud.githubusercontent.com/assets/13177534/21304423/038f3728-c600-11e6-956f-d4858b748fcf.JPG)

And here's how it "showed" in TOC.

![1](https://cloud.githubusercontent.com/assets/13177534/21304433/12f98196-c600-11e6-8905-fa16ace5454f.JPG)

**Comment by wengan-li** [comment]
Although I am still little bit confused, but I think I got your point.

If you want the TOC show as:
```
2.1 Introduction
    a. Definitions
    b.  ...
    ... ...
```

You should use the following in `conf.tex`:
```
\SetNumberingFormat[SubSection]{%
  BeginText = {}, EndText = {},
  TextAlign = {Left},
  CNumStyle = {}, SNumStyle = {}, SSNumStyle = {LowerAlph},
  SepAtIndex = {.}, SepBetweenCnS = {}, SepBetweenSnSS = {},
} % End of \SetNumberingFormat{}
```

But if you want the TOC show as:
```
2.1 Introduction
    Definitions
    ...
    ...
```

You should try this:
```
\SetNumberingFormat[SubSection]{%
  BeginText = {}, EndText = {},
  TextAlign = {Left},
  CNumStyle = {}, SNumStyle = {}, SSNumStyle = {},
  SepAtIndex = {}, SepBetweenCnS = {}, SepBetweenSnSS = {},
} % End of \SetNumberingFormat{}
```

Is this fit your needs ?

**Comment by yusie1978** [comment]
Not really, i am sorry for your misconception...

I don't mean like those two examples you gave... what I mean is, in my chapter 2 (for example), there is as following:
-----------------------------
Chapter 2    Introduction
2.1 Background
...
a. Application Examples I   %--> which is a subsection or subsubsection 
b. Application Example II
..
2.2 Problem Statements
2.3 Design Controllers

Then, in my TOC, we'll have:
-----------------------------
Chapter 2. Introduction
2.1 Background
2.2 Problem Statements
2.3 Design Controllers
-----------------------------
where there is no letter 'a' or 'b' in TOC for "application example I" and "application example II", respectively.

Best regards,

Yusie

**Comment by wengan-li** [comment]
I got your point now.

First you need to make sure that the `\SetNumberingFormat{}` **ONLY** exist in `conf.tex`.

In you case, I think it is a subsection:
```
Chapter 2 Introduction
2.1 Background
...
a. Application Examples I %--> I think this should be a subsection
b. Application Example II
..
2.2 Problem Statements
2.3 Design Controllers
```

So use the following command in `conf.tex`:
```
\SetNumberingFormat[SubSection]{%
  BeginText = {}, EndText = {},
  TextAlign = {Left},
  CNumStyle = {}, SNumStyle = {}, SSNumStyle = {LowerAlph},
  SepAtIndex = {.}, SepBetweenCnS = {}, SepBetweenSnSS = {},
} % End of \SetNumberingFormat{}
```

If you see the TOC show this again:
```
Chapter 2. Introduction
2.1 Background
2.2 Problem Statements
2.3 Design Controllers
```

Then you **MUST** exist `\SetNumberingFormat[SubSection]{ ... }` somewhere else which overwrite the configure above:
```
\SetNumberingFormat[SubSection]{%
  BeginText = {}, EndText = {},
  TextAlign = {Left},
  CNumStyle = {}, SNumStyle = {}, SSNumStyle = {},
  SepAtIndex = {}, SepBetweenCnS = {}, SepBetweenSnSS = {},
} % End of \SetNumberingFormat{}
```

So your target is:
1. Erase all `\SetNumberingFormat[SubSection]{ ... }` from all files including the commented line from files `conf.tex` and `context/...`
2. Compile and check what will show in the TOC
3. Re-insert the command into `conf.tex` to do the configure

**Comment by yusie1978** [comment]
Thank you!!!

**Comment by wengan-li** [comment]
Please feel free to let me know if you need any further assistance.
