### ISSUE TITLE
Pandoc支援

### ISSUE THREAD

**Issue by extraymond** [wengan-li/ncku-thesis-template-latex#23]
想請教一下，如果我想要用pandoc markdown撰寫，然後用您的模板作為基底輸出，是可行的嘛？
我對latex還不太熟QQ

**Comment by wengan-li** [comment]
唔~
你提到一個非常有趣的使用方式.

我大約看了一下Pandoc的使用方式,
用簡單來回答你的問題的話:
```
想法上沒問題, 但現行的模版沒法提供相對應的接合方式.

而實作出那個接合方式需要一定的時間來研究, 同時沒法保證能100%跟Latex的版本有同樣的效果.
```
所以我覺得這想法可行.
但我覺得預期提供這功能只給Markdown的使用者,
使用這麼出時間去做這接合.
倒不如想出一個新的使用方式, 
同時能提供給Word, Latex, Markdown或其他方式的使用者更來得有效.

**Comment by extraymond** [comment]
謝謝！

我是因為看到 [有人](https://github.com/chiakaivalya/thesis-markdown-pandoc) 實做的方式，也是用類似大大的latex這樣，將檔案的方格處理，跟內容輸入分開。
然後pandoc也是用-V這個參數，去呼叫latex改字體等等，或用preamble去調整。

如果也是用一樣的思維，pandoc輸出成doc或是html等格式的方式應該都是類似的。
這樣的話，也許markdown可以讓大家比較專注在撰寫內容上。
另外，讓markdown的內容用git管理的時候，刪減的內容變得一目了然。我想這些對大家寫作的過程應該都會有所幫助。

**Comment by extraymond** [comment]
補充找到的中文說明
[pandoc與學術論文](http://zale.site/articles/2016/05/Academia-Writing-Using-Markdown-and-Pandoc.html)

**Comment by wengan-li** [comment]
看完你提供的內容後,
的確看這簡單例子會覺得的確做得成的,
但我覺得需要思考的問題不少.

問題:
1. 由於是轉換給新工具使用, 故這模板做到怎麼, 才能套用在新工具上 ? 例如:
    * Pandoc是不是要這模板要壓縮成一個`.latex`檔之後給`--template`才能使用呢 ? 不是的話又怎才能使用呢 ?
    * Pandoc看起來是使用CLI的方式來使用. 問題假如什麼都不懂的人, 就只懂在GUI按幾下就希望能馬上把自己的論文轉換出來, 這個有沒有什麼好方法處理呢 ?
    * 看起來要把所有的論文檔案都要一個一個的給Pandoc, 有什麼方式可以自動這行為, 而不用人手一個一個去輸入呢 ? (單單這模板的有關模板的資料夾`thesis/template`都已經有47個檔案了)
    * Latex跟Markdown能不能共存在同一個檔案中 ? 因為我看你所提供的[例子](https://github.com/chiakaivalya/thesis-markdown-pandoc), 雖然是`.md`為檔名, 但內容是latex, 我好像看不到有一個檔案中是使用latex + markdown的寫法. 那最大的問題是, 你會有多少的內容, 是用不到這模板提供的功能呢 ?

2. 對現有模板提供的效果或功能有沒有任何影響 ? 例如:
    * 排板的位置 (任何位置錯亂都影響到繳交, 而不能繳交就影響學位)
    * Latex中的基本功能. Markdown有很多Latex的基本功能是做不到, 但你不能保證不會有任何同學不會去用到這些功能. 故如果有同學想使用這些功能時, 他們要怎在markdown中使用呢 ? 例如:
        - Page Number
        - Indent, space
        - Chapter, Section, SubSection的Header引用 (在Markdown如何引用`#`, `##`等等的標題 ?)
        - Chapter, Section的Numbering, 例如 `Chapter 1. Abc`, `Chapter 2. Def`. (在Markdown能不填寫這數字都能自動產生出來嗎 ? 這功能重要喔, 假如有10個Chapter, 同學可能單單因為你要自己輸入就不會用你的模板喔, 起碼我是這一類的人)
    * 這模板所包裝的功能, 例如:
        - 自定numbering的格式
        - 插入Figure / Table配合一些簡單的設定, 來使用複雜的功能, 如 背景透明, 放大放小.
        - 口試文件的樣板


我的markdown可能沒有比你的好.
假如我進度緩慢, 每個小問題要解決1星期,
那我簡單來算一下, 就是需要13個星期, 即是3個月左右.
(不要少看1個功能, 我單單把[numbering](https://github.com/wengan-li/ncku-thesis-template-latex/issues/12#issue-156131650)和[其修改/更新](https://github.com/wengan-li/ncku-thesis-template-latex/issues/12#issuecomment-223289785)都已經弄了2~3星期, 之後還在修正這功能的問題. 所以預期1星期已經算快了)

那下一個最大的問題是,
我值不值得用3個月把這模板弄到Pandoc來使用呢 ?
我會覺得重寫一個直接使用全Markdown的模板會來得更快.

我不是覺得使用Pandoc不好,
只是覺得應該有更好的處理方式而已.

-------

另外, 你對Latex有一些誤會.
以我所知道是用來編寫論文的工具中,
主要分2派:
1. Word派 (Google Docs, Microsoft Word)
2. 純文本派 (Latex, Markdown, R, etc.)
基本上只要是純文本派都能在用Git管理的時候, 變動的內容變得一目了然.

--------------------------------------------------------------------------

其實我做這模板出來, 就是為了`讓大家只專注在撰寫論文內容上`.
而不是去煩惱論文格式, 排板 和 中英文編寫中任何的問題.
我不敢說這模板做得很好,
我只敢說這模板比一些實驗室中多年傳程下來的模板更方便, 更多功能.

**Comment by wengan-li** [comment]
話是這樣說,
對我們純文本派的人來講, 能支援其他的純文本,
的確能幫助更多的人.
但是不論這模板支援多少其他的純文本,
還是沒法幫助最大眾的word派, 這才是問題所在.

所以就如同我說
我覺得應該能有另一個更好的方法,
同時能幫助那些不論哪一派, 都需要這模板的人.
