### ISSUE TITLE
無法產生reference

### ISSUE THREAD

**Issue by PornProvider** [wengan-li/ncku-thesis-template-latex#25]
as title
無法產生reference頁面 導致引用失敗

**Comment by wengan-li** [comment]
你好

請提供
1. 模版的版本 (請參考你手上的ChangeLog.md)
2. 你手上的檔案 (thesis/conf/conf.tex 和 thesis/context/context.tex)
3. 你所使用的作業系統和其版本
4. 你所使用的MiKTeX和Texmaker的版本
5. 攝影一張當 '無法產生reference頁面' 時的錯誤畫面或log
以方便讓我找出問題點在哪

**Comment by wengan-li** [comment]
你好

我剛剛去實驗了
```
OS: Window 7 x64 / Window 10 x64 (1709)
MiKTex: miktex-2.9.6361-x64
Texmaker: version 5.0.2
Template: v1.5.2
```
把所有的工具和系統更新到最新版，
並直接使用`thesis/thesis.tex`，產生pdf的內容正常。

所以可能是你的輸入內容產生錯誤，
以導致無法產生你的reference頁面。

或是請提供錯誤的螢幕畫面或Texmaker的log檔案，
以方便讓我能幫助你找出問題點在哪。
