### ISSUE TITLE
參考文獻問題

### ISSUE THREAD

**Issue by wuwuyi** [wengan-li/ncku-thesis-template-latex#26]
參考文獻生成都沒有問題，但是有沒有方法能讓中英文獻分開呢?
另外想問如果是使用apa格式，有什麼方法能讓文獻列表有號碼呢? 例如像Item一樣

**Comment by wengan-li** [comment]
十分抱歉，最近十分忙碌，忘了回應你

請問你所想的中英文獻分開是指怎樣的分開 ？
分開2個chapter 或是 先列出中文之後再列出英文 之類 ?
如果是這2種的話，以我所知道好似是沒法做到的。

現時模版的APA格式是當時為@wenhsinhu 在[Issue#9](https://github.com/wengan-li/ncku-thesis-template-latex/issues/9)而做的。
我找到最新用來[提供APA格式的package](https://ctan.org/pkg/apa6)，它的Pack­age doc­u­men­ta­tion中shortsample好似是沒有顯示數字的。
[有人提到apa格式原本就沒數字](https://tex.stackexchange.com/questions/373336/apa-bibliography-style-with-numbers)，所以如果真的想用，好似要暴力的改coding。
你真的需要有數字的APA ? [可以先參考其他格式呢](https://pt.sharelatex.com/learn/Bibtex%20bibliography%20styles#Biblatex_styles)。
