### ISSUE TITLE
Order of reference

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#27]
Why the order of the reference is not similar as in IEEE journal? i.e. the first shown must be [1], not jump to [25]? Is there any way, we can change the order of reference?

Regards,

Yusie

**Comment by wengan-li** [comment]
Try take a look to [use unsrt style](https://tex.stackexchange.com/questions/17354/sort-thebibliography-by-citation-order).

It seem I was missed to provide this option.
Let me add it back.

**Comment by wengan-li** [comment]
It seem the template has already provided this feature.

Try this one in your `conf/conf.tex`
```
\SetupReference{%
  Title = {\TextDefaultTitleReferenceEng},
  BibStyle = {unsrt},
} % End of \SetupReference{}
```

**Comment by yusie1978** [comment]
Yes, I just tried it, and it works!!!!

Thanks a lot!!!
