### ISSUE TITLE
ncku.tex

### ISSUE THREAD

**Issue by abby50066** [wengan-li/ncku-thesis-template-latex#28]
成大內頁邊界是：上23mm、下35mm（含頁碼）、左30mm、右25mm
但在 ncku.tex中是: 直式:上2.3cm、下3.5cm(含頁碼)、左2.5cm、右3cm

左右相反，希望可以更新template。

謝謝

**Comment by wengan-li** [comment]
感謝你通知我

已更新至[v1.5.3](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.5.3)
