### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hirokiht** [wengan-li/ncku-thesis-template-latex#29]
Should be Tainan, Taiwan, R.O.C.
https://github.com/wengan-li/ncku-thesis-template-latex/blob/b62aba4e39aeca8951942b0a4b399ae4eeb46f99/thesis/template/oral/template/template-eng.tex#L71

**Comment by wengan-li** [comment]
Thanks for notifying.
It took so long to discover that I was typo.
Even my thesis is also incorrect ~.~ . 

Updated to [v1.5.4](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.5.4)

**Comment by yusie1978** [comment]
I am sorry, I was curious what is the problem (about Tainan, Taiwan, R.O.C) ? so that next time i can also modify my dissertation.

Thanks

**Comment by wengan-li** [comment]
@yusie1978 After you asking what is the problem of the address.
I got another question that I was forgotten a long time ago.
```
1. Why the Oral Document has an address in the English version but not exist in Chinese version ?
2. Can we have an example to follow ? Alternatively, follow the Chinese version without any address  ?
```

Based on there is no a standard example of the Oral Document.
When I was coding this template a long time ago, I went to the library to reference the Thesis and Dissertation which were submitted and stored there.
I referenced about ~10 Thesis and Dissertation and some of the template from some of our CSIE's lab. Also with some example from Google about the format of Oral Document in Thesis and Dissertation.
I don't remember why I coded like this after all.

So to make sure this Oral Document looks professional.
I sent the email to our [NCKU ETCS](http://etds.lib.ncku.edu.tw/html/) asking for help.
I hope they may provide some useful answer.

However, if not, what's you guy suggest ?

**Comment by wengan-li** [comment]
Thx for their quick response.
Here is the mail they reply me.

```
您好

如同教務處回覆，應使用教務處所提供之版本為主。

謝謝您

----國立成功大學 圖書館系統管理組 數位論文小組-----
70101 台南市大學路一號
Tel: (06)2757575 ext. 65773
Fax: (06)2378232
Email: etds@email.ncku.edu.tw


-----Original Message-----
From: 成大課務組(祺惠) [mailto:z10510040@email.ncku.edu.tw] 
Sent: Monday, July 23, 2018 10:42 AM
To: etds@email.ncku.edu.tw
Cc: @@呂組長秋玉
Subject: Re: FW: 查問有關論文中的學位考試合格證明內容

電子學位論文小組您好:


有關貴單位文中提供的學位考試合格證明書與本校學位考試系統中列印的證明書並不相符
請問夾帶檔中之學位考試合格證明書來源?
並請轉知學生以本校學位考試系統中列印之學位考試合格證明書為主

謝謝
祝平安順心


----------------------------------
成功大學課務組 黃祺惠
Tel: 06-2757575轉50157 
Fax: 06-2766411
Mail：z10510040@email.ncku.edu.tw
----------------------------------
```

課務組 said [my example](https://github.com/wengan-li/ncku-thesis-template-latex/files/2219867/example.oral-phd.pdf) is not match with the output from the [學位考試系統](https://campus4.ncku.edu.tw/wwwmenu/program/mou/).
Then this really surprising me, my example was checked and confirm able to use 3 years ago.
May be it need to update now.
This may take some time to confirm this.

Could you guy able to download the 證明書 from 學位考試系統 ?
I would like to have an example to let me re-design the layout if needed.
Or use to reply to them for more help.
