### ISSUE TITLE
學位考試合格證明書與成大學校學位考試系統中列印的證明書並不相符

### ISSUE THREAD

**Issue by wengan-li** [wengan-li/ncku-thesis-template-latex#30]
Following the Issue #29.

I was sent mail to [NCKU ETCS](http://etds.lib.ncku.edu.tw/html/) asking for help about the oral document.
And thx for their quick response.
Here is the mail they reply me.

```
您好

如同教務處回覆，應使用教務處所提供之版本為主。

謝謝您

----國立成功大學 圖書館系統管理組 數位論文小組-----
70101 台南市大學路一號
Tel: (06)2757575 ext. 65773
Fax: (06)2378232
Email: etds@email.ncku.edu.tw


-----Original Message-----
From: 
Sent: Monday, July 23, 2018 10:42 AM
To: etds@email.ncku.edu.tw
Subject: Re: FW: 查問有關論文中的學位考試合格證明內容

電子學位論文小組您好:


有關貴單位文中提供的學位考試合格證明書與本校學位考試系統中列印的證明書並不相符
請問夾帶檔中之學位考試合格證明書來源?
並請轉知學生以本校學位考試系統中列印之學位考試合格證明書為主

謝謝
祝平安順心


----------------------------------
```

For privacy protection, I hid some names and emails.

課務組 said [my example](https://github.com/wengan-li/ncku-thesis-template-latex/files/2219867/example.oral-phd.pdf) is not match with the output from the [學位考試系統](https://campus4.ncku.edu.tw/wwwmenu/program/mou/).
Then this really surprising me, my example was checked and confirm able to use 3 years ago.
May be it need to update now.
This may take some time to confirm this.

Could you guy able to download the 證明書 from 學位考試系統 ?
I would like to have an example to let me re-design the layout if needed.
Or use to reply to them for more help.

**Comment by abby50066** [comment]
[P76054208論文證明書.pdf](https://github.com/wengan-li/ncku-thesis-template-latex/files/2228593/P76054208.pdf)

**Comment by wengan-li** [comment]
Thx @abby50066, this file is helpful.
Because of I am no longer able to access that system.

I don't remember the format from the platform when I applied for my graduation.
However, it seems very new to me.

I am going to use this file to ask 課務組 is there any English version for this document.
By the [thesis specification](http://cid.acad.ncku.edu.tw/ezfiles/56/1056/img/730/degree4-1.pdf), it mentions that all thesis (including doctor and master) should write in full English version.
But not including this document which makes me feel uncomfortable (by my OCD).

**Comment by wengan-li** [comment]
For your privacy protection, I just use this image to ask them.

![oral-doc](https://user-images.githubusercontent.com/6211564/43334854-bac552b0-9200-11e8-93cf-93ef444176f3.png)

**Comment by abby50066** [comment]
OK~

**Comment by wengan-li** [comment]
Sorry for the late reply - I was really busy these few months.
Let me update you guys what I know.

課務組 responded with following message (which I took the critical parts from emails): 
```
...
口試合格證明書，請使用教務處所提供之正式版本!
因此，建議用文字提示說明，請學生至相關系統去下載較為適當。

另外，口試合格證明書為教務處之正式文件，本數位論文小組並無相關範例可提供。
...
有關文中提到英文版論文證明書，目前尊重各系所自行處理
另，本校並未授權學生或系所使用任何模板設計本校論文證明書
論文證明書請以本校學位考試系統列印為主
繳交論文時，亦請檢附由學位考試系統列印之論文證明書
若您需要您的論文證明書，請逕洽貴系所學位考試承辦人協助列印
...
```
In summary:
1. Chinese version of 學位考試論文證明書 (Defense certificate) **SHOULD BE** use the PDF from [學位考試系統](https://campus4.ncku.edu.tw/wwwmenu/program/mou/), which look like [this](
https://github.com/wengan-li/ncku-thesis-template-latex/issues/30#issuecomment-408477513). (But not forced)
2. The decision of English version of defense certificate in left to each college/department. But I haven't found any standards from any college/department yet.
3. Far as I know, the 電子學位論文小組 hasn't rejected the template generated Chinese defense certificate. But still, they recommend using the PDF from 學位考試系統.

I have already marked this note into [v1.5.6](https://github.com/wengan-li/ncku-thesis-template-latex/releases).

**Comment by wengan-li** [comment]
@yusie1978 So it seems you don't need to change anything.
