### ISSUE TITLE
eng name of CSIE is wrong

### ISSUE THREAD

**Issue by abby50066** [wengan-li/ncku-thesis-template-latex#31]
In thesis/template/command/cmd-department.tex:
"Insitute" should be "Institute".

**Comment by wengan-li** [comment]
Thx. Fixed and updated to [v1.5.5](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.5.5).

Damm, it was wrong for three years. And no one saw it, including me.
And I just submitted my thesis with this typo !
