### ISSUE TITLE
How to add a reference in Caption of Figure?

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#33]
Hi, 

I have a problem how to add a reference in my Figure's Caption.

Let say I have three figures: a, b, and c. 
Each one has a reference (I took this figure from one source---so I have three sources).
Then, I want to show that Figure a, b, and c with their reference, that looks like this, e.g:

                   [ Figure a, Figure b, and Figure c]
a. unicycle robot1 [31], b. unicycle robot2 [50], and c. unicycle robot3 [60]

Here's the codes that cause error:
------------------------------------
\InsertFigure
      [scale=0.70,
        caption={Development of Unicycle Robots: (a) Unicycle without turn-table \RefBib{ho2014balance}, (b) Unicyle with turn-table \RefBib{ke2013path}, (c) Light-weight unicycle robot\RefBib{chin2016balance}},
      opacity=0.4]
      {./context/unicycle-robot/state_of_art.jpg}
-----------------------------------
Can you suggest me how should i solve this?

Thank you.

**Comment by wengan-li** [comment]
Try this
```
\captionsetup[figure]{labelformat=empty}

\InsertFigure[...]{...}

\captionsetup[figure]{labelformat=default}
```

**Comment by yusie1978** [comment]
Hi,

I have tried the following codes:
---------------------------
\captionsetup[figure]{labelformat=empty}
\InsertFigure
      [scale=0.70,
        caption={Development of Unicycle Robots: (a) Unicycle without turn-table \RefBib{ho2014balance}, (b) Unicyle with turn-table \RefBib{ke2013path}, (c) Light-weight unicycle robot\RefBib{chin2016balance}},
        label={fig_development},
        opacity=0.4]
      {./context/unicycle-robot/state_of_art.jpg}
\captionsetup[figure]{labelformat=default}

-------------------------
but it didn't work.
![aaa](https://user-images.githubusercontent.com/13177534/50037554-97286700-004d-11e9-96c4-3eaf4b67aa89.jpg)

**Comment by wengan-li** [comment]
I found out it was the define of \InsertFigure{...}.
I haven't found out how to fix it yet.

Try this one,
```
\begin{figure}[H]%
\begin{minipage}[c]{\textwidth}%
    \begin{mdframed}[skipabove=0pt, skipbelow=0pt, leftmargin=0pt, rightmargin=0pt,
    innerleftmargin=0pt, innerrightmargin=0pt, innertopmargin=0pt,
    innerbottommargin=0pt, linewidth=0pt, apptotikzsetting={%
    \tikzset{mdfbackground/.append style={opacity=0.4}}}]%
    \makebox[\textwidth]{\includegraphics[scale=0.7]{./example/introduction/pic/by-nc-sa.png}}%
    \end{mdframed}%
\end{minipage}%
\caption*{Development of Unicycle Robots: (a) Unicycle without turn-table \RefBib{ho2014balance}, (b) Unicyle with turn-table \RefBib{ke2013path}, (c) Light-weight unicycle robot\RefBib{chin2016balance}}
\end{figure}%
```
This should be work for your case.

**Comment by yusie1978** [comment]
Hi,

I have tried it and it works!!

Thank you!!
