### ISSUE TITLE
Reference 無法產生

### ISSUE THREAD

**Issue by Jyun-Neng** [wengan-li/ncku-thesis-template-latex#34]
我使用的是 mac os 10.14.2
我直接使用以下指令編譯 thesis.tex
```
xelatex thesis.tex
```
會找不到 reference 
會出現以下問題
```
LaTeX Warning: Citation `testpage:bib:book:justice' on page 249 undefined on in
put line 97.
```
我用的是範例來編譯
請問這該怎麼解呢？

**Comment by wengan-li** [comment]
您好，

可參考[Demo Doc](
https://github.com/wengan-li/ncku-thesis-template-latex-sample/blob/master/thesis%20(demo).pdf) 中的`Chapter 3 - 產生 PDF 的流程`中提到正式編譯的做法為
```
XeLaTeX -> BibTex -> XeLaTeX -> 瀏覽 PDF
```

您這個Warning是應該您只做了
```
XeLaTeX -> 瀏覽 PDF
```
缺少了.bib檔的內容，就會出現這種Warning.

所以如果只是編寫內容, 引用的內容和號碼不是重要的話, 看不到都沒問題，則直接使用這方式來編譯是沒問題。
但如果要看到引用號碼的話，則請使用`XeLaTeX -> BibTex -> XeLaTeX`來編譯。

**Comment by ChampDBG** [comment]
您好，
想借題分享 [Latexmk](https://mg.readthedocs.io/latexmk.html)。如 @wengan-li 所述，在 latex 中需要額外針對 BibTex 進行編譯，有時甚至需要編譯一次以上， Latexmk 可以代為處理這個過程，個人在以下情況成功使用。

---

#### 使用環境
* Windows 10
* MikTex 2.9.6972
* TexMaker 5.0.3

#### Prerequisite
* Perl (Latexmk 是 perl script)
* 安裝 Latexmk (不同作業系統安裝方式不同，請參考上述連結)

#### 設定
在 "TexMaker > 選項 > 設定 TexMaker > 快速編譯 > User" 的空格填入

```
latexmk -e "$pdflatex=q/xelatex -synctex=1 -interaction=nonstopmode/" -pdf %.tex
```

---

個人沒有在 Mac 環境上測試過，官方文件有提到 Mac 中的安裝、使用、其他設定 (ex: 編譯後 preview...)。

另外除了 Latexmk 以外，還有其他可以自動處理編譯的方法，有興趣請參考 [[link](https://tex.stackexchange.com/questions/30330/how-can-i-avoid-compiling-twice)]。
