### ISSUE TITLE
How to make number of references as IEEE

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#37]
Hallo..

I have one issue regarding how to make the citation numbers in body text looks like [12-15] (as in IEEE standard) instead of [12,13,14,15] as following:

![nomor](https://user-images.githubusercontent.com/13177534/58963051-0c941980-87df-11e9-834c-f8a26103a66a.jpg)

Could you fix this problem?

Thank you

Yusie R

**Comment by wengan-li** [comment]
Hi,

Sorry, busy day.

The template seem not support IEEE format yet.
Let me check and update you when it ready.

Thank you.

**Comment by wengan-li** [comment]
Sorry,

I just having Issue #39,
I still can't able to check the code yet.

**Comment by wengan-li** [comment]
@yusie1978 
I just tried [`ieeetr` of Bibtex bibliography styles](https://www.overleaf.com/learn/latex/Bibtex_bibliography_styles) and [IEEEtran](https://ctan.org/pkg/ieeetran?lang=en) style without success.
Could you find me a workable Latex file which shows the cite number as your request ?

**Comment by yusie1978** [comment]
Hi, Sorry for the late response..

Here I attach my conf. paper which is workable example for bibtex bibliography style.
In order to follow [1-4] format, we use the following command:

\renewcommand{\citedash}{--}
\renewcommand{\citepunct}{,}

Results from the latex :
![HASIL](https://user-images.githubusercontent.com/13177534/60141122-a94a4580-97e6-11e9-8e15-e79c836df79f.jpg)



----------LATEX CODES IS STARTING FROM HERE --------------------


%
\documentclass[conference]{IEEEtran}

\ifCLASSINFOpdf
   \usepackage[pdftex]{graphicx}
  % declare the path(s) where your graphic files are
   \graphicspath{{../pdf/}{../jpeg/}}
  % and their extensions so you won't have to specify these with
  % every instance of \includegraphics
   \DeclareGraphicsExtensions{.pdf,.jpeg,.png}
\else
 
\fi

\usepackage{amsmath} % assumes amsmath package installed
\usepackage{amssymb}  % assumes amsmath package installed
\usepackage{color}
\usepackage{cite}
\usepackage{algorithmic}

\renewcommand{\citedash}{--}
\renewcommand{\citepunct}{,}

\begin{document}

\title{Balance Control of Reaction Wheel Pendulum}

\maketitle


\begin{abstract}
%\boldmath
This paper presents the balance control of reaction wheel pendulum system...
\end{abstract}

\IEEEpeerreviewmaketitle

%----------------------------------------------------
\section{Introduction}
%----------------------------------------------------
% no \IEEEPARstart
This is an example of the problem being asked \cite{rizal2015point,chen2017dynamic,rizal2014balance}, another example is this \cite{zhu2015adaptive,chen2017dynamic}, and this \cite{chen2017dynamic}. 

\bibliographystyle{IEEEtran}

\begin{thebibliography}{1}

\bibitem{rizal2015point}
Y. Rizal, CT Ke, and MT Ho, "Point-to-point motion control of a unicycle robot: Design, implementation, and validation," in Proc. IEEE Int. Conf. Robotics and Automation, pp. 4379--4384, 2015.
\bibitem{chen2017dynamic}
Z Chen, X Ruan, and Y Li, "Dynamic Modeling of a Cubical Robot Balancing on Its Corner," in Proc. MATEC Web of Conferences, pp. 1--6, 2017.
\bibitem{rizal2014balance}
Y. Rizal, JW Syu, and MT Ho, "Balance control of an inverted pendulum system using second-order sliding mode control," in Proc. CACS Int. Automatic Control Conf. pp. 191--196, 2014.
\bibitem{zhu2015adaptive}
YH Zhu, YS Gao, CH Xu, J Zao, H Jin, and J Lee, "Adaptive control of a gyroscopically stabilized pendulum and its application to a single-wheel pendulum robot," \emph{IEEE/ASME Transactions on Mechatronics}, vol. 20, no. 5, pp. 2095--2106, 2015
\end{thebibliography}

\end{document}

**Comment by wengan-li** [comment]
@yusie1978 
Sorry, I really forgot about this issue.
Heavy workload on work for now.

I should be free some more times in August.

I am really sorry that I need to hold this progress right now.

**Comment by yusie1978** [comment]
It's ok.. I can wait...

thank you...

**Comment by wengan-li** [comment]
@yusie1978 
I am really sorry that I was so late.
I was remember this issue everyday, but I am not ready to handle it.
I know this is late, but I hope this still work for you.

I just checked your example and add it into this template.
I don't have the idea to make it simple.
But still it works.

To use IEEEtran style:

1. Update to [v1.5.9](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.5.9)
2. Uncomment the code in `configure.tex`
```
% \usepackage{cite}
% \renewcommand{\citedash}{--}
% \renewcommand{\citepunct}{,}
```

3. Update `con.tex`
```
\SetupReference{%
  BibStyle = {IEEEtran},
}
```

4. Use it in your thesis, for example:
```
\RefBib{thesis1, thesis2, thesis3}
```

I hope you can still enjoy this template.

**Comment by yusie1978** [comment]
Hi,

I just change the configure.tex and con.tex file in my original version. It works fine as I expected.

Good job!!!

Thank you

Yusie
