### ISSUE TITLE
參考文獻問題

### ISSUE THREAD

**Issue by soupstandstop** [wengan-li/ncku-thesis-template-latex#43]
不好意思，我在Overleaf上使用
我的流程是
1. 先從Google scholar選定paper，複製其bib，接著放進thesis/context/references/paper.bib
2. 再打開thesis/context/references/references.tex中的這一行\ReferencesFiles{./context/references/paper}
3. 打開thesis/conf/conf.tex中這一行\SetupReference{%
  Title = {\TextDefaultTitleReferenceEng},
  BibStyle = {plain},
} 
4. 接著在使用\RefBib{標題}去引用文獻
但是compile完出現的是[?]以及References那一頁也沒有顯示我paper.bib裡面放的參考文獻

想請問以上流程哪裡出錯了，我是新手煩請解惑T_T 謝謝～

**Comment by wengan-li** [comment]
Hi @soupstandstop,

非常抱歉，
近期本人無法抽身專心去回應你們的問題，
所以對此十分抱歉。

不知道你是否還在使用這模版呢？
你要的答案可以在[說明文件](https://github.com/wengan-li/ncku-thesis-template-latex-sample/blob/master/thesis%20(demo).pdf)中的`Chapter 3 本模版使用教學`中的`產生 PDF 的流程`找到，你要做`XeLaTeX ­> BibTex ­> XeLaTeX ­> 瀏覽 PDF`，這樣才會顯示References number.
