### ISSUE TITLE
封面日期的產出問題

### ISSUE THREAD

**Issue by MOHOAzure** [wengan-li/ncku-thesis-template-latex#44]
以 conf.tex 中的 SetCoverDate 指令來設置論文封面的日期 時，若輸入的月份以數字 0 開頭，則無法正常輸出日期。

舉例來說，SetCoverDate{2019}{07} 將導致論文封面的日期只呈現 "2019" 而沒有月份資料。若是改輸入為SetCoverDate{2019}{7} 則能夠正常呈現 "July 2019"。

建議的修補辦法:
1. 補充註解，說明月份的撰寫格式不能以數字 0 開頭
2. 修改指令，讓用戶設置月份時能以數字 0 開頭

另外，設置口試日期的指令為 SetOralDate，該指令在設置月份或日期時也可能有類似的問題。

**Comment by wengan-li** [comment]
@MOHOAzure 
非常抱歉，我應該1、2個月前就已經fix好。
但好似個腦飛走了，完全忘了這回事。

已update成 [v1.5.8](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.5.8)
