### ISSUE TITLE
圖片編號

### ISSUE THREAD

**Issue by Lu-Yi-Hsun** [wengan-li/ncku-thesis-template-latex#45]
圖片編號有包含chapter 1.1該怎麼改成依序的1,2,3編碼

**Comment by Lu-Yi-Hsun** [comment]
@wengan-li

**Comment by wengan-li** [comment]
@Lu-Yi-Hsun 
抱歉，工作有點急，沒空上來看。

請問你的問題解決了嗎？
沒的話能給一個例子嗎？

謝謝

**Comment by Lu-Yi-Hsun** [comment]
@wengan-li 
感謝回覆 
我自己解決了

如果有相同需求的可以在此下載修改的template
https://github.com/Lu-Yi-Hsun/template/tree/thu?files=1
