### ISSUE TITLE
portrait and landscape orientations

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#46]
Hi,
I have a question whether we can use portrait and landscape orientation at the same time?
For example in page 1-10, I use portrait orientation, then for longer table in page 11 I use landscape orientation and followed with another portrait orientation from page 12 to the rest of chapter.

Thanks a lot

Yusie

**Comment by wengan-li** [comment]
Hi,

Does this sample result that you want ?
```
\documentclass{article}

\usepackage{lscape}

\begin{document}

Page 1
Hello World.

\begin{landscape}
\newpage
Page 2
Hello World again.
\end{landscape}

\end{document}
```

If yes, try this:

1. Add line into `template\configure.tex`
```
\usepackage{lscape}
```

2. Add this 2 line before and after the new page command
```
\begin{landscape}
\StartNewPage
...
\EndOfPage
\end{landscape}
```

**Comment by yusie1978** [comment]
Hi,
It actually works but not that simple because I found the layout of the page is not correct .

\begin{landscape}
\StartNewPage
  \InsertTable
    [caption={Systematic Literature Review.},
      label={table:literature-reviews}]
    {
      \begin{tabular}{l l l l l}  \hline
       \textbf{References} & \textbf{Year} & \textbf{Topic}  & \textbf{Control Method} & \textbf{Research Approach} \\  \hline
      Schoonwinkel \RefBib{schoonwinkel1987design} & 1986 & Stabilization control & Nonlinear control & Experimentation\\ 
      David W. Vos \RefBib{vos1990dynamics,vos1992nonlinear} & 1990, 1992 & Stabilization control & Nonlinear adaptive control & Experimentation  \\
      \end{tabular}
    } % End of \InsertTable

\EndOfPage
\end{landscape}

And the result is as follow (see the number of page hit the first column):

![page](https://user-images.githubusercontent.com/13177534/70383634-06f4d780-19ac-11ea-95db-53079c921585.jpg)

**Comment by wengan-li** [comment]
What happen when you type some content after the table ?
```
\InsertTable{}
...
Text Text Text Text Text
...
\EndOfPage
\end{landscape}
```

Could you help me found some sample code that the page number will move to the bottom of the landscape page ?
I just found some code with the same result, without moving the page number.

Also why you need landscape page ?
Figure and table able to rotate 90 degree which are built-in feature.

**Comment by wengan-li** [comment]
@yusie1978 Yo~
Did you found a way to workaround ?
