### ISSUE TITLE
您好，我以您的樣板為基礎，做了一個幾乎全中文化的EMBA論文

### ISSUE THREAD

**Issue by timloo0710** [wengan-li/ncku-thesis-template-latex#5]
這裏只能放圖片 ，我這幾天再整理到我的GITHUB。

1。修改的地方，中文化的目次，第一章，第一節。
2。浮水印須從內文第一章列印時，圖次會有浮水印，加上CLEAR PAGE可修正。
3。封面微調一下。
4。英文摘要自己手工加上英文關鍵字，(和中文關鍵字不同)
5。加上空白頁。
6。謝誌放到中英文摘要之後。
7。口試教授的簽名頁，只有中文簽名一頁。不用英文簽名頁。

**Comment by wengan-li** [comment]
十分的高興聽到你這樣說.
非常希望這個模板能幫你提供基本的功能.

我預計這幾星期會進行一個大改版,
更新一些功能和修正排版上的問題,
到時候你可以再更新到你的版本中.
而且你說的修改, 都給了我一些新靈感來當成未來的修改.

-----------------------------------------------------

可以問一下你的'2.'的意思嗎 ?
因為除在了幾頁特殊頁面外,
浮水印全都要出現在所有頁面,
所以你的'Clear Page'用途是 ?

關於'5.'的空白頁用途是 ?

另外EMBA的'考試合格證明'只要中文就好了 ?
這真的是盲點.

**Comment by wengan-li** [comment]
我已更新v1.3.0
有大量的修改, 應該能處理你提到的一些問題.

**Comment by wengan-li** [comment]
你好
因為很久沒聽到你的下文,
所以不知道進展如何呢 ?

我暫時先把這issue關掉,
如你再有問題, 歡迎重開的.
