### ISSUE TITLE
reference 無法顯示

### ISSUE THREAD

**Issue by Louis8582** [wengan-li/ncku-thesis-template-latex#50]
將 context.tex 中的 \input{./context/references/references} 開啟，但沒有顯示內容
其他的 input 倒是都正常

**Comment by wengan-li** [comment]
@Louis8582 
請問如何沒有顯示內容 ?
是整個Reference的頁面沒了，或是\Ref 的部份只顯示 [?] ?

**Comment by wengan-li** [comment]
@Louis8582 
請先嘗試做了XeLaTex -> BibTex -> XeLaTex，這應該會能把Reference的頁面建出來。
之後如果在Reference的頁面中沒有任何一個reference, 即是您沒有在內文中使用\RefTo{}.

**Comment by wengan-li** [comment]
@Louis8582 您最後有沒有試到原因嗎？

**Comment by Louis8582** [comment]
抱歉最近比較多事情，沒上來回覆
上次透過你說的方式 XeLaTex -> BibTex -> XeLaTex 有成功，
但後來在新增加的 bib 就又無法顯示，感到很困惑。

**Comment by wengan-li** [comment]
@Louis8582 
這個是正常的，
每次更新bib後，
都要重複做XeLaTex -> BibTex -> XeLaTex 才會更新的。
所以比較推薦您先專注內容，
bib再一次過更新。

**Comment by Louis8582** [comment]
可是我確實有重新編譯過 還是無法顯示內容！

**Comment by wengan-li** [comment]
嗯。。。。。。。。
聽起來是建立BibTex的問題，
您能否cap screen 把所產出來的PDF畫面和Latex的error給我看嗎？

**Comment by Louis8582** [comment]
<img width="948" alt="截圖 2020-07-24 下午6 29 33" src="https://user-images.githubusercontent.com/23739360/88382864-f2027280-cddb-11ea-84d5-40c42daa3f89.png">
<img width="959" alt="截圖 2020-07-24 下午6 30 34" src="https://user-images.githubusercontent.com/23739360/88382876-f7f85380-cddb-11ea-8b92-cc02e09c7ea9.png">
<img width="590" alt="截圖 2020-07-24 下午6 31 38" src="https://user-images.githubusercontent.com/23739360/88382878-f9298080-cddb-11ea-9417-852b51dd15d2.png">
像是這樣嗎？

**Comment by wengan-li** [comment]
嗯。。。。。。。。。。
根據您的Bib 我有7個reference連不起來
<img width="1226" alt="Screenshot 2020-07-25 at 10 24 58 PM" src="https://user-images.githubusercontent.com/6211564/88459164-d8d5f080-cec5-11ea-95d7-e7dc28e1435f.png">
但你沒有什麼的error message。

能再給我看你在內文 `\RefTo{9130724}`, `\RefTo{9093068}`, `\RefTo{9007407}` 和`\RefTo{9007407}`  所產出來PDF的畫面嗎？
如果reference失敗，至少會顯示`[?]`。 

正式情況是如果Bib沒被reference,
即是您在內文沒有使用這個reference code。

**Comment by Louis8582** [comment]
意思是如果沒有 reference 他就不會顯示的意思嗎？ 我記得我之前引用是沒有問題的。

目前論文引用索引我是用 \ref{}的指令使用，編譯後結果如下圖所示能出現有顯示的references。
<img width="811" alt="截圖 2020-07-26 上午2 18 42" src="https://user-images.githubusercontent.com/23739360/88463579-56115d80-cee6-11ea-8d3b-67b12871e7ec.png">

**Comment by neeon-li** [comment]
>>>`意思是如果沒有內文沒有鏈結到的 reference 它就不會顯示的意思嗎？`
根據我的使用經驗，對的。
您可以隨便\RefTo 試一下看看嗎？

**Comment by Louis8582** [comment]
我加上去了
編譯得結果顯示 ?? ，並且在 reference 中並沒有新增內容出來

**Comment by wengan-li** [comment]
顯示`[?]`的話, 
有3個可能性，
1. 您未ref
2.您已ref, 但未做`XeLaTex -> BibTex -> XeLaTex`
3. 您已ref, 已做`XeLaTex -> BibTex -> XeLaTex`, 您ref 錯code 或 reference 的內容有些錯誤，這一項慢慢debug了

如果你的情況是3, 你能否給我那個bib reference, 我嘗試看是什麼可能.

**Comment by wengan-li** [comment]
@Louis8582 
成功找到原因嗎？

**Comment by Jingnix** [comment]
想請問我也是遇到同樣的問題。
我是用 \cite{} 去連接reference，
但還是會出現 [?]  
想請問上面提到的 \RefTo{} 的意思是？

**Comment by wengan-li** [comment]
Hi @Jingnix,
請問已做`XeLaTex -> BibTex -> XeLaTex`嗎 ?
如果已做了的話，能否share 部份您的file, 已方便我檢查 ？
而且請問你是用哪個版本的template ?

**Comment by Jingnix** [comment]
@wengan-li 我是用最新版本的template
但關於做 XeLaTex -> BibTex -> XeLaTex 的部分
因為我是用 Overleaf 寫的，不知道這個部分是否需要做？

**Comment by Jingnix** [comment]
已解決，
我用Overleaf寫，在reference.tex的部分
{./context/references/paper} 改成 {thesis/context/references/paper}即可

**Comment by wengan-li** [comment]
@Jingnix 
很高興聽到您已解決了這問題。
那我把這issue close掉，有新問題的話歡迎新開issue來問。
