### ISSUE TITLE
系所缺漏

### ISSUE THREAD

**Issue by kuangyoli** [wengan-li/ncku-thesis-template-latex#51]
您好，在設定系所\SetDept時，數據科學研究所似乎沒有被加入名單之中，可以煩請您確認一下嗎？謝謝。

**Comment by wengan-li** [comment]
你好，

抱歉呢，
請問是[這一個](http://ds.ncku.edu.tw/)嗎 ？ 
可能是我當年的時候，這個所還未成立。

謝謝

**Comment by kuangyoli** [comment]
您好，是的。
我後來有自行在文件裡新增系所，所以問題以解決，但是可能要麻煩您幫忙新增一下，再更新github。

謝謝

Wen-Gan Li ***@***.***>於 2021年6月11日 週五，上午11:03寫道：

**Comment by wengan-li** [comment]
@kuangyoli
請問系所的縮寫 IDS, 全寫是Institute of Data Science嗎？

**Comment by wengan-li** [comment]
@kuangyoli 
已增加`\SetDeptIDS` 在 `v1.5.11`. 
謝謝你的提出。

**Comment by kuangyoli** [comment]
Thanks a lot!

Wen-Gan Li ***@***.***> 於 2021年6月14日 週一 下午12:03寫道：
