### ISSUE TITLE
InsertFigures file not found

### ISSUE THREAD

**Issue by Ting199708** [wengan-li/ncku-thesis-template-latex#52]
您好，

我在使用\insertFigures時將perrow設為3會發生如下圖的error，想請問是哪邊需要修正，下圖二是我所打的latex code

謝謝

![image](https://user-images.githubusercontent.com/33084926/121328659-178e6100-c947-11eb-8394-b1ca9c1e890f.png)
![image](https://user-images.githubusercontent.com/33084926/121328739-2c6af480-c947-11eb-80a6-e4af2a4be087.png)

**Comment by wengan-li** [comment]
你好，

抱歉，
請給我一些時間去測試。

謝謝

**Comment by wengan-li** [comment]
@Ting199708 
我已找到原因，是在`\InsertFigures`中的bug.
已在[v1.5.12](https://github.com/wengan-li/ncku-thesis-template-latex/releases/tag/v1.5.12)修正。

或你直接更新 `/thesis/template/command/cmd-figures.tex` 這檔案就可了。
謝謝

**Comment by Ting199708** [comment]
謝謝更新！
