### ISSUE TITLE
用Overleaf網站編輯、編譯

### ISSUE THREAD

**Issue by b3326023** [wengan-li/ncku-thesis-template-latex#56]
感謝分享!

想請問這個模板，有沒有辦法用 [Overleaf ](https://www.overleaf.com/)網站來編輯、編譯呢?

**Comment by wengan-li** [comment]
@b3326023 你好

抱歉呢。
我個人沒有使用 Overleaf，但根據之前的其他同學所問，
我猜想是應該沒有問題，但可能做一些設定，但詳細是什麼我不太清楚。
https://github.com/wengan-li/ncku-thesis-template-latex/issues/50
https://github.com/wengan-li/ncku-thesis-template-latex/issues/43

**Comment by b3326023** [comment]
感謝! 原來的確是要做些設定，在 Overleaf 的左上角 Menu，把 Compiler 改為 XeLaTex、Main document 改成 thesis/thesis.tex 就可以了! 
![image](https://user-images.githubusercontent.com/15379209/122365103-f8b64d00-cf8c-11eb-973b-79bc7d0c4ffc.png)


以前都不知道 Overleaf 原來也可以設定這些功能，沒問題了，感謝您!

**Comment by wengan-li** [comment]
感謝你的分享。
希望這些說明都能幫到以後要用的同學們。

**Comment by ycl0112** [comment]
你好，想請問一下我已經照著上面步驟在overleaf中設定，但是仍然不能正常編譯，不知道是在哪邊設定是否有錯誤
![image](https://github.com/wengan-li/ncku-thesis-template-latex/assets/89286986/95fcd668-74e6-48e5-99a5-78dec798854b)
