### ISSUE TITLE
中文版封面日期對齊

### ISSUE THREAD

**Issue by kevinmaura** [wengan-li/ncku-thesis-template-latex#57]
您好：
當我把 conf.tex 中的語言封面設定調整成 \DisplayCoverInChi 時，最下方的日期變成最左方對齊了，我能用甚麼方法把它改成跟英文版一樣的置中對齊嗎?
附上的圖片為使用原本的檔案，只有把Demo模式關掉與調整封面語言後去編譯的封面
![擷取](https://user-images.githubusercontent.com/81506840/141250191-3f8766e6-e8b5-4b00-b74f-8d56178a2491.JPG)

**Comment by wengan-li** [comment]
@kevinmaura 非常抱歉沒有留意到您的留言，希望您已解決這問題。

@maglili 感謝幫忙解答，已根據您的方法進行更新，如果下次您發現又有問題，歡迎使用pull request來提供修改。

已根據這次issue進行了更新v1.5.13。
