### ISSUE TITLE
成大畢業論文內頁不需要浮水印

### ISSUE THREAD

**Issue by Josh-WANGJS** [wengan-li/ncku-thesis-template-latex#59]
你好
我在圖書館系統組(負責審核論文格式的單位)實習過2年，如果內文有浮水印我們會一律退回，現在學校的系統浮水印會自己生成，所以其實不用浮水印了。謝謝。

**Comment by wengan-li** [comment]
您好 @Josh-WANGJS ,

感謝提供這情報，
想詳細請問，我理解為：

`印刷版 - 實體`
拿去影印店的那個PDF版本，是`需要`在內頁中包含學校浮水印

`電子版`
交去系統組時，是`不需要`在內頁中包含學校浮水印

是這個意思嗎？

謝謝

**Comment by Josh-WANGJS** [comment]
你好
沒錯，此外，我記得是如果你先上傳到系統組，系統就會幫你生成浮水印，然後你去影印的時候，用系統生成的檔案就可以了。當然你也還是可以用有浮水印的檔案拿去影印，然後用沒有浮水印的檔案上傳到系統組。
謝謝

Wen-Gan Li ***@***.***> 於 2023年1月29日 週日 15:36 寫道：

**Comment by wengan-li** [comment]
感謝說明。

已更新到 [v1.6.0](https://github.com/wengan-li/ncku-thesis-template-latex/blob/v1.6.0/CHANGELOG.md), 移除預設的浮水印。
同時在`README.md`新增`學位論文上傳和列印說明`, 以說明浮水印何時出現，和何時需要。
