### ISSUE TITLE
關於章節標題顯示1.1, 1.1.1

### ISSUE THREAD

**Issue by tenyang1999** [wengan-li/ncku-thesis-template-latex#61]
你好
我在說明中Ch3的模板使用教學中>論文基本設定中16章節標題預設為
![image](https://github.com/wengan-li/ncku-thesis-template-latex/assets/92511534/23207cae-02c7-4574-9b55-b4c2b907d81c)

但是在complie之後卻沒有前面的編號，且在查看本說明書的標題們後發現好像也是一樣沒有前面編號
![image](https://github.com/wengan-li/ncku-thesis-template-latex/assets/92511534/3e076f7c-c889-4652-b36a-89edde2e9b9f)

想要請問預設是否是有編號的?若是希望能夠有編號要怎麼辦，謝謝~

**Comment by wengan-li** [comment]
Hello @tenyang1999,

感謝你發現呢個小差別，我完全沒發現這一點。

根據現在最後所產出來的[範例 PDF v1.5.7](https://github.com/wengan-li/ncku-thesis-template-latex-sample/blob/5ab2f8a1cf2617f563cf0fc4ff41afb8a94da906/thesis%20(demo).pdf)，
和根據最後還有編號的[範例 PDF v1.5.2](https://github.com/wengan-li/ncku-thesis-template-latex-sample/commit/7d7bcb8566ea4405675aa36edaff3bcf536d7847)，
的確原本最早期時設計時，
的確`應該是有前面編號`。

由於已經相距當時時間很遠，
而因為這個編號會影響很多地方的顯示，
根據 [CHANGELOG.md](https://github.com/wengan-li/ncku-thesis-template-latex/blob/master/CHANGELOG.md)的記錄，
應該我不會特別故意關了這個的顯示。

所以暫時想到有可能Latex的package有更新過一些設定而我沒留意到，
我會去看看發生什麼事，
而且會去參考最新其他同學們的Latex code的模版，
以修正這個問題。

這需要我一些時間，
抱歉要你等待一會。

**Comment by tenyang1999** [comment]
> Hello @tenyang1999,
> 
> 感謝你發現呢個小差別，我完全沒發現這一點。
> 
> 根據現在最後所產出來的[範例 PDF v1.5.7](https://github.com/wengan-li/ncku-thesis-template-latex-sample/blob/5ab2f8a1cf2617f563cf0fc4ff41afb8a94da906/thesis%20(demo).pdf)， 和根據最後還有編號的[範例 PDF v1.5.2](https://github.com/wengan-li/ncku-thesis-template-latex-sample/commit/7d7bcb8566ea4405675aa36edaff3bcf536d7847)， 的確原本最早期時設計時， 的確`應該是有前面編號`。
> 
> 由於已經相距當時時間很遠， 而因為這個編號會影響很多地方的顯示， 根據 [CHANGELOG.md](https://github.com/wengan-li/ncku-thesis-template-latex/blob/master/CHANGELOG.md)的記錄， 應該我不會特別故意關了這個的顯示。
> 
> 所以暫時想到有可能Latex的package有更新過一些設定而我沒留意到， 我會去看看發生什麼事， 而且會去參考最新其他同學們的Latex code的模版， 以修正這個問題。
> 
> 這需要我一些時間， 抱歉要你等待一會。

不好意思，
想請問是否已經有修正過的版本了，
因為近期在撰寫論文，沒有編號的版本讀起來實在會蠻困難的
謝謝。

**Comment by wengan-li** [comment]
@tenyang1999 
你好，抱歉弄了有點久。

已更新到 v1.7.0. 
原來發現這東西是我在 `conf.tex`中開了一些設定，
只要你重新關掉那些就可。
可參考 [這邊的變動](https://github.com/wengan-li/ncku-thesis-template-latex/commit/494d9b30d3aea899ec2b9cef0e8fa26a0d56d654).

麻煩你更新 `thesis/template/configure.tex` 到最新版，
和把 `conf.tex` 中的 `\SetNumberingFormat[Section]`和`\SetNumberingFormat[SubSection]`關掉就可。

**Comment by tenyang1999** [comment]
@wengan-li 
你好，有按照你的方式修改好了，目前數字的部分沒有問題~
非常感謝你的幫忙~
