### ISSUE TITLE
Where to place `usepackage` command?

### ISSUE THREAD

**Issue by Nana2929** [wengan-li/ncku-thesis-template-latex#65]
Thank you for the template. 
I need something like `verbatim` environment but with auto word wrap. The internet forums suggest using `listings` but it needs import and setup. I didn't find where to place the imports and setup commands (tried `conf.tex`, does not work).

**Comment by wengan-li** [comment]
Hello @Nana2929 ,

if you need to use `usepackage`, you can take a look at `thesis/template/configure.tex`.

**Comment by Nana2929** [comment]
Thank you for the reply. I've checked that `thesis/template/configure.tex` does include the `\usepackage` commands and will use it for my import commands hereafter. Closing the issue as the problem was resolved.
