### ISSUE TITLE
``\InsertFigure`` does not allow `\cite` in caption. 

### ISSUE THREAD

**Issue by Nana2929** [wengan-li/ncku-thesis-template-latex#66]
# Description

I'd like to cite something inside a figure's caption. 
Latex naturally supports it with `\includegraphics` command (as in second example), but `\InsertFigure` (in this template) will show red compilation errors (as the first example). My latex compiler is XeLatex 2023 (provided by Overleaf). This also leads me to wonder if we must use `\InsertFigure`, since using `\includegraphics` seems to display as well, and the figure appears on **List of Figure** section as expected. 
```latex
% does not work
\InsertFigure[scale=0.5,caption={The four key elements in the expected output sentiment tuple of ABSA (\cite{Zhang2023ABSASurvey}},label={fig:absa}] 
{context/related-work/images/keys-in-absa.png}

% works
\begin{figure}[h]
    \centering
    \includegraphics[scale=0.5]{context/related-work/images/keys-in-absa.png}
    \caption{The four key elements in the expected output sentiment tuple of ABSA (\cite{Zhang2023ABSASurvey})}
    \label{fig:keys-in-absa}
\end{figure}
```
# Error Messages  
![截圖 2024-07-02 下午5 05 49](https://github.com/wengan-li/ncku-thesis-template-latex/assets/58811089/76401f1c-69a4-46f2-949c-06f77ae7cb5a)

**Comment by wengan-li** [comment]
Hello @Nana2929,

Have you tried `\RefTo{}` ?

Sometimes, the helper commands do not work with some Latex syntax, as I mention in `Objective`:
```
    某些包裝出來的語法, 可能會在一些情況下會產生衝突而令LaTex不接受, 這時候有2種做法:
    \begin{enumerate}
      \item
      {
        不使用某些寫法, 例如已知的`\verb|\InsertFigure|'沒法被包在Table, minipage或framebox中.
      } % End of \item{}

      \item
      {
        如真的要使用那些情況, 那就不要使用模版提供的語法, 而直接去寫LaTex原版的語法.
      } % End of \item{}
    \end{enumerate}
```

In your case,
I think you need to use figure block to bypass.
```
\begin{figure}[h]
  ...
\end{figure}
```

**Comment by Nana2929** [comment]
Sorry for my late reply. Thank you for providing this workaround. Knowing that Latex-inherited syntax works is a relief.
