### ISSUE TITLE
使用不同的格式引用文獻

### ISSUE THREAD

**Issue by loveakai** [wengan-li/ncku-thesis-template-latex#9]
您好！感謝您提供模板讓我們使用。目前我遇到一個問題，因為敝系使用不同的引用方式(APA)，但是我不太知道這個模板要如何更改引用方式，期望您能夠提供一些意見。
一般而言，使用APA格式引用是這樣設定：
\usepackage{apacite}

\bibliographystyle{apacite}
\bibliography{mybib}

我曾經試過在ncku/configure.tex中加入\usepackage{apacite}與在contex/contex.tex中加入\bibliographystype{apacite}，無法使用。
我也試過在references/references.tex中加入\bibliographystyle{apacite}並更改\ReferencesFiles{./context/references/mybib}，一樣無法使用。
最後我嘗試更改command/reference.tex中這一行\bibliographystyle{abbrv}，改為\bibliographystyle{apacite}也無法使用。

想請問是不是我有什麼地方沒有改到，或是有其他的設定方式呢？謝謝您！

**Comment by wengan-li** [comment]
你好,
感謝支持, 有人願意使用就是我最大的精神食糧.

請去下載新的'v1.3.2'.
我在conf.tex新增了一些控制去處理你的需求.
你去更新你的'ncku'資料夾, 在'conf.tex'插入'\BibStyleUseApacite', 之後重新build應該就會OK.

其實你嘗試的做法是對的.
在'configure.tex'加入\usepackage{apacite}, 
修改'cmd-references.tex'中使用\bibliographystyle{apacite}.
就行了

起碼我第一次測時就已經OK了. 我沒有看到你的錯誤message是什麼, 所以不知道原因了.
你可以去讀一下我在新'conf.tex'有關'Reference和引用時的格式'中相關的說明, 可能那就是你遇到的問題了.

**Comment by loveakai** [comment]
您好，今天到實驗室馬上就測試了，依照您的方法修正後，目前可以用了，感謝您。
因我使用的是texmaker與miktex，因此一樣第一次compile .tex檔後再compile .aux檔，之後再compile 1-2次.tex檔，之後就可以成功使用APA格式引用了，謝謝！
我會在謝誌中提到您的：）

**Comment by wengan-li** [comment]
只要你有使用就已經很感謝了.
其實只是跟同學分享或幫助樣版改進,
就已經十分足夠了,
不一定要在謝誌提到這樣版.
